<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue'
import { api,apiObjectUrl } from '../../api'
import { useMerchantContext } from '../../stores/merchantContext'
const c=useMerchantContext(), tab=ref('dashboard'), questions=ref<any[]>([]), observations=ref<any[]>([]), facts=ref<any[]>([]), dashboard=ref<any>({})
const q=ref<any>({questionText:'',city:'佛山',district:'九江镇',industry:'美容',consumerScenario:'',targetAudience:'',budgetText:'',decisionStage:'CONSIDERATION',commercialValue:3,targetPlatforms:['XHS_DIANDIAN','MEITUAN_WENXIAOTUAN'],enabled:true,demo:false,notes:''})
const o=ref<any>({questionId:'',aiPlatform:'MEITUAN_WENXIAOTUAN',observationMode:'MANUAL_APP',observedAt:new Date().toISOString(),locationText:'佛山九江镇',rawAnswer:'',screenshotAssetId:null,merchantMentioned:false,merchantRecommended:false,recommendationRank:null,factCheckStatus:'NOT_CHECKED',citedSources:[],mentionedCompetitors:[],competitorText:'',citationText:'',verificationStatus:'VERIFIED',demo:false,notes:''})
const issue=ref<any>({factId:'',issueType:'WRONG_VALUE',observedValue:'',severity:'MEDIUM',resolved:false,resolutionNotes:''})
const merchantId=computed(()=>c.merchant.value?.id)
async function load(){if(!merchantId.value)return;const id=merchantId.value;[questions.value,observations.value,facts.value,dashboard.value]=await Promise.all([api(`/merchants/${id}/consumer-questions`),api(`/merchants/${id}/ai-observations`),api(`/merchants/${id}/facts`),api(`/merchants/${id}/ai-observations/dashboard`)]);if(!o.value.questionId&&questions.value[0])o.value.questionId=questions.value[0].id}
watch(merchantId,load);onMounted(load)
async function saveQuestion(){await api(`/merchants/${merchantId.value}/consumer-questions`,{method:'POST',body:JSON.stringify(q.value)});q.value.questionText='';await load()}
async function saveObservation(){const payload={...o.value,mentionedCompetitors:o.value.competitorText?o.value.competitorText.split(/[，,]/).filter(Boolean).map((name:string)=>({name:name.trim(),recommended:true})):[],citedSources:o.value.citationText?o.value.citationText.split(/[，,]/).filter(Boolean).map((url:string)=>({sourceType:'MANUAL',sourceName:'人工录入',url:url.trim()})):[]};await api(`/merchants/${merchantId.value}/ai-observations`,{method:'POST',body:JSON.stringify(payload)});o.value.rawAnswer='';o.value.competitorText='';o.value.citationText='';await load()}
async function addIssue(id:string){await api(`/merchants/${merchantId.value}/ai-observations/${id}/fact-issues`,{method:'POST',body:JSON.stringify(issue.value)});await load()}
async function createTask(id:string,reasonCode:string){await api(`/merchants/${merchantId.value}/ai-observations/${id}/create-task`,{method:'POST',body:JSON.stringify({reasonCode})});await c.refresh()}
async function upload(file:File){const f=new FormData();f.append('file',file);o.value.screenshotAssetId=(await api('/assets',{method:'POST',body:f})).id}
async function preview(id:string){window.open(await apiObjectUrl(`/assets/${id}/content`),'_blank','noopener')}
</script>
<template>
  <section class="module-page"><div class="module-heading"><div><span class="eyebrow">AI OBSERVATION CENTER</span><h2>AI观察</h2><p>人工记录消费者问题与点点、问小团、豆包、DeepSeek的回答；不会自动登录、操作或抓取第三方平台。</p></div></div>
    <el-tabs v-model="tab">
      <el-tab-pane label="指标概览" name="dashboard"><div class="metric-grid"><div class="metric-card" v-for="x in [['观察次数',dashboard.totalObservations],['提及率',dashboard.mentionRate],['推荐率',dashboard.recommendationRate],['TOP3率',dashboard.top3Rate],['事实准确率',dashboard.factAccuracyRate],['覆盖平台',dashboard.observedPlatformCount]]" :key="String(x[0])"><small>{{x[0]}}</small><b>{{typeof x[1]==='number'&&String(x[0]).includes('率')?(Number(x[1])*100).toFixed(1)+'%':x[1]??'—'}}</b></div></div><div class="module-columns"><div class="panel"><h3>平台表现</h3><el-table :data="dashboard.platformBreakdown||[]"><el-table-column prop="platform" label="平台"/><el-table-column prop="observations" label="观察"/><el-table-column prop="mentioned" label="提及"/><el-table-column prop="recommended" label="推荐"/><el-table-column prop="top3" label="TOP3"/></el-table></div><div class="panel"><h3>主要竞品</h3><div v-for="x in dashboard.topCompetitors||[]" :key="x.name" class="data-row"><b>{{x.name}}</b><small>出现 {{x.mentions}} 次</small></div><h3>最近事实错误</h3><div v-for="x in dashboard.recentFactIssues||[]" :key="x.id" class="data-row"><b>{{x.issue_type}}</b><small>{{x.observed_value}}</small></div></div></div></el-tab-pane>
      <el-tab-pane label="消费者问题" name="questions"><div class="module-columns"><div class="panel"><h3>问题库</h3><div v-for="x in questions" :key="x.id" class="data-row"><b>{{x.question_text}}</b><small>{{x.decision_stage}} · 商业价值 {{x.commercial_value}} · 观察 {{x.observation_count}}</small></div></div><div class="panel"><h3>新增消费者问题</h3><el-input v-model="q.questionText" type="textarea" placeholder="例如：佛山九江镇哪里适合做脸部清洁？"/><el-select v-model="q.decisionStage"><el-option v-for="x in ['AWARENESS','CONSIDERATION','COMPARISON','DECISION','AFTER_SALE']" :key="x" :value="x"/></el-select><el-input-number v-model="q.commercialValue" :min="1" :max="5"/><el-button type="primary" :disabled="!q.questionText" @click="saveQuestion">保存问题</el-button></div></div></el-tab-pane>
      <el-tab-pane label="观察记录" name="observations"><div class="module-columns"><div class="panel"><h3>录入人工观察</h3><el-select v-model="o.questionId" placeholder="选择消费者问题"><el-option v-for="x in questions" :key="x.id" :value="x.id" :label="x.question_text"/></el-select><el-select v-model="o.aiPlatform"><el-option v-for="x in ['XHS_DIANDIAN','MEITUAN_WENXIAOTUAN','DOUBAO','DEEPSEEK']" :key="x" :value="x"/></el-select><el-input v-model="o.rawAnswer" type="textarea" :rows="6" placeholder="粘贴完整、未经改写的AI回答"/><el-checkbox v-model="o.merchantMentioned">提及商家</el-checkbox><el-checkbox v-model="o.merchantRecommended">明确推荐</el-checkbox><el-input-number v-model="o.recommendationRank" :min="1" placeholder="推荐排名"/><el-select v-model="o.factCheckStatus"><el-option v-for="x in ['NOT_CHECKED','CORRECT','ERROR']" :key="x" :value="x"/></el-select><el-input v-model="o.competitorText" placeholder="竞品名称，逗号分隔"/><el-input v-model="o.citationText" placeholder="引用链接，逗号分隔"/><el-upload :auto-upload="false" :show-file-list="false" accept="image/png,image/jpeg,image/webp" :on-change="(f:any)=>upload(f.raw)"><el-button>上传截图</el-button></el-upload><el-button type="primary" :disabled="!o.questionId||!o.rawAnswer" @click="saveObservation">保存观察</el-button></div><div class="panel"><h3>观察记录</h3><div v-for="x in observations" :key="x.id" class="data-row"><el-tag v-if="x.demo" type="warning">DEMO M3</el-tag><b>{{x.ai_platform}} · {{x.question_text}}</b><small>提及：{{x.merchant_mentioned?'是':'否'}} · 推荐：{{x.merchant_recommended?'是':'否'}} · 排名：{{x.recommendation_rank||'—'}}</small><p>{{x.raw_answer.slice(0,120)}}…</p><el-button v-if="x.screenshot_asset_id" link @click="preview(x.screenshot_asset_id)">查看截图</el-button><el-button link type="primary" @click="createTask(x.id,x.fact_check_status==='ERROR'?'FACT_ERROR':x.merchant_recommended?'COMPETITOR_DOMINANCE':'NOT_RECOMMENDED')">创建整改任务</el-button><el-collapse><el-collapse-item title="新增事实错误"><el-select v-model="issue.factId" placeholder="关联商家事实（可选）"><el-option v-for="f in facts" :key="f.id" :value="f.id" :label="f.factType+' · '+f.normalizedText"/></el-select><el-input v-model="issue.observedValue" placeholder="AI回答中的错误内容"/><el-select v-model="issue.issueType"><el-option v-for="t in ['WRONG_VALUE','WRONG_ADDRESS','WRONG_PHONE','WRONG_BUSINESS_HOURS','MISSING_KEY_SERVICE','NON_EXISTENT_SERVICE','WRONG_STOREFRONT','UNVERIFIED_CLAIM']" :key="t" :value="t"/></el-select><el-button :disabled="!issue.observedValue" @click="addIssue(x.id)">保存事实错误</el-button></el-collapse-item></el-collapse></div></div></div></el-tab-pane>
    </el-tabs>
  </section>
</template>
