package com.mengwei.localgrowth.fact;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mengwei.localgrowth.audit.AuditService;
import com.mengwei.localgrowth.identity.AuthService.Identity;
import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Immutable fact versions; merchant_facts only points to the currently selected version. */
@Service
public class FactCenterService {
  private static final Set<String> SCOPES=Set.of("BRAND","STOREFRONT");
  private static final Set<String> STATES=Set.of("UNVERIFIED","VERIFIED","EXPIRED","DISPUTED");
  private static final Set<String> BRAND_TYPES=Set.of("BRAND_NAME","BRAND_ALIAS","HISTORICAL_NAME","SERVICE_ITEM","TARGET_AUDIENCE","QUALIFICATION","PROMOTABLE_CLAIM","PROHIBITED_CLAIM","CASE_STUDY","MEDIA_ASSET");
  private static final Set<String> STOREFRONT_TYPES=Set.of("STORE_NAME","ADDRESS","GEO_LOCATION","PHONE","BUSINESS_HOURS","SERVICE_AREA","PARKING_AND_TRANSIT","PRICE_RANGE","PACKAGE","CONTACT_METHOD","CASE_STUDY","MEDIA_ASSET");
  private final JdbcTemplate jdbc; private final AuditService audit; private final ObjectMapper json;
  public FactCenterService(JdbcTemplate jdbc,AuditService audit,ObjectMapper json){this.jdbc=jdbc;this.audit=audit;this.json=json;}

  public Map<String,Object> summary(Identity i,UUID merchantId){
    merchant(i,merchantId);
    Map<String,Object> result=new LinkedHashMap<>(); result.put("brand",primaryBrand(i,merchantId)); result.put("storefronts",storefronts(i,merchantId));
    Map<String,Object> counts=jdbc.queryForMap("select count(*) filter(where v.status='VERIFIED') as verified, count(*) filter(where v.status='UNVERIFIED') as unverified, count(*) filter(where v.status='EXPIRED') as expired, count(*) filter(where v.status='DISPUTED') as disputed, count(*) filter(where v.status not in ('EXPIRED','DISPUTED') and (v.effective_from is null or v.effective_from<=now()) and (v.effective_to is null or v.effective_to>=now())) as \"currentEffective\", count(*) as total from merchant_facts f join merchant_fact_versions v on v.id=f.current_version_id and v.tenant_id=f.tenant_id where f.tenant_id=? and f.merchant_id=? and not f.deleted",i.tenantId(),merchantId);
    result.put("counts",counts); return result;
  }
  /** Provisioning for merchants created after the legacy V10 backfill. */
  @Transactional public void initializeMerchant(Identity i,UUID merchantId,String merchantName){
    var existing=jdbc.queryForList("select id from brand_profiles where tenant_id=? and merchant_id=? and is_primary and not deleted",i.tenantId(),merchantId); if(!existing.isEmpty()) return;
    OffsetDateTime now=OffsetDateTime.now(); UUID brandId=UUID.randomUUID(),storeId=UUID.randomUUID();
    jdbc.update("insert into brand_profiles (id,tenant_id,merchant_id,legal_name,is_primary,deleted,created_at,updated_at,created_by,updated_by,version) values (?,?,?,?,?,?,?,?,?,?,?)",brandId,i.tenantId(),merchantId,merchantName,true,false,now,now,i.userId(),i.userId(),0L);
    jdbc.update("insert into storefronts (id,tenant_id,merchant_id,brand_id,name,is_primary,deleted,created_at,updated_at,created_by,updated_by,version) values (?,?,?,?,?,?,?,?,?,?,?,?)",storeId,i.tenantId(),merchantId,brandId,merchantName,true,false,now,now,i.userId(),i.userId(),0L);
    audit.log(i.tenantId(),i.userId(),"BRAND_PROFILE_CREATED","BrandProfile",brandId,"创建主品牌档案："+merchantName);
    audit.log(i.tenantId(),i.userId(),"STOREFRONT_CREATED","Storefront",storeId,"创建默认主门店："+merchantName);
  }
  public List<Map<String,Object>> brands(Identity i,UUID merchantId){ merchant(i,merchantId); return jdbc.queryForList("select bp.id,bp.legal_name as name,b.website,coalesce(b.aliases,'') as aliases,coalesce(b.services,'') as services,coalesce(b.claims,'') as claims,bp.is_primary as \"isPrimary\",bp.version,bp.created_at as \"createdAt\",bp.updated_at as \"updatedAt\" from brand_profiles bp left join lateral (select website,aliases,services,claims from brands b where b.tenant_id=bp.tenant_id and b.merchant_id=bp.merchant_id and not b.deleted order by b.created_at limit 1) b on true where bp.tenant_id=? and bp.merchant_id=? and not bp.deleted order by bp.is_primary desc,bp.created_at",i.tenantId(),merchantId); }
  public Map<String,Object> primaryBrand(Identity i,UUID merchantId){merchant(i,merchantId); return one("select id,legal_name as name,is_primary as \"isPrimary\",version,created_at as \"createdAt\",updated_at as \"updatedAt\" from brand_profiles where tenant_id=? and merchant_id=? and is_primary and not deleted",i.tenantId(),merchantId);}
  public List<Map<String,Object>> storefronts(Identity i,UUID merchantId){ merchant(i,merchantId); return jdbc.queryForList("select s.id,s.brand_id as \"brandId\",s.name,s.is_primary as \"isPrimary\",s.version,s.created_at as \"createdAt\",s.updated_at as \"updatedAt\" from storefronts s where s.tenant_id=? and s.merchant_id=? and not s.deleted order by s.is_primary desc,s.name",i.tenantId(),merchantId); }
  @Transactional public Map<String,Object> createStorefront(Identity i,UUID merchantId,StorefrontInput in){
    merchant(i,merchantId); UUID brandId=in.brandId()==null?uuid(primaryBrand(i,merchantId).get("id")):in.brandId(); requireBrand(i,merchantId,brandId); UUID id=UUID.randomUUID(); OffsetDateTime now=OffsetDateTime.now();
    if(in.primary()) jdbc.update("update storefronts set is_primary=false,updated_at=?,updated_by=?,version=version+1 where tenant_id=? and merchant_id=? and brand_id=? and not deleted",now,i.userId(),i.tenantId(),merchantId,brandId);
    jdbc.update("insert into storefronts (id,tenant_id,merchant_id,brand_id,name,is_primary,deleted,created_at,updated_at,created_by,updated_by,version) values (?,?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),merchantId,brandId,in.name(),in.primary(),false,now,now,i.userId(),i.userId(),0L);
    audit.log(i.tenantId(),i.userId(),"STOREFRONT_CREATED","Storefront",id,"创建门店："+in.name()); return storefront(i,merchantId,id);
  }
  @Transactional public Map<String,Object> updateStorefront(Identity i,UUID merchantId,UUID storefrontId,StorefrontUpdate in){
    Map<String,Object> old=storefront(i,merchantId,storefrontId); if(((Number)old.get("version")).longValue()!=in.expectedVersion()) throw conflict(); OffsetDateTime now=OffsetDateTime.now();
    if(in.primary()) jdbc.update("update storefronts set is_primary=false,updated_at=?,updated_by=?,version=version+1 where tenant_id=? and merchant_id=? and brand_id=? and id<>? and not deleted",now,i.userId(),i.tenantId(),merchantId,uuid(old.get("brandId")),storefrontId);
    int changed=jdbc.update("update storefronts set name=?,is_primary=?,updated_at=?,updated_by=?,version=version+1 where id=? and tenant_id=? and merchant_id=? and version=? and not deleted",in.name(),in.primary(),now,i.userId(),storefrontId,i.tenantId(),merchantId,in.expectedVersion()); if(changed!=1)throw conflict();
    audit.log(i.tenantId(),i.userId(),"STOREFRONT_UPDATED","Storefront",storefrontId,"更新门店："+in.name()); return storefront(i,merchantId,storefrontId);
  }
  public List<Map<String,Object>> facts(Identity i,UUID merchantId,UUID storefrontId){
    merchant(i,merchantId); String sql="select f.id,f.brand_id as \"brandId\",f.storefront_id as \"storefrontId\",f.fact_scope as \"factScope\",f.fact_type as \"factType\",f.fact_key as \"factKey\",f.current_version_id as \"currentVersionId\",f.version,v.value_json::text as \"valueJson\",v.normalized_text as \"normalizedText\",v.status,v.effective_from as \"effectiveFrom\",v.effective_to as \"effectiveTo\",v.verification_notes as \"verificationNotes\",v.source_summary as \"sourceSummary\",v.created_at as \"versionCreatedAt\" from merchant_facts f join merchant_fact_versions v on v.id=f.current_version_id and v.tenant_id=f.tenant_id where f.tenant_id=? and f.merchant_id=? and not f.deleted";
    List<Object> args=new ArrayList<>(List.of(i.tenantId(),merchantId)); if(storefrontId!=null){requireStorefront(i,merchantId,storefrontId);sql+=" and (f.storefront_id=? or f.fact_scope='BRAND')";args.add(storefrontId);} sql+=" order by f.fact_scope,f.fact_type,f.created_at"; return jdbc.queryForList(sql,args.toArray());
  }
  public Map<String,Object> fact(Identity i,UUID merchantId,UUID factId){Map<String,Object> f=factRow(i,merchantId,factId);f.put("evidenceLinks",links(i,factId,uuid(f.get("currentVersionId"))));return f;}
  public List<Map<String,Object>> versions(Identity i,UUID merchantId,UUID factId){factRow(i,merchantId,factId);return jdbc.queryForList("select v.id,v.fact_id as \"factId\",v.value_json::text as \"valueJson\",v.normalized_text as \"normalizedText\",v.status,v.effective_from as \"effectiveFrom\",v.effective_to as \"effectiveTo\",v.verification_notes as \"verificationNotes\",v.source_summary as \"sourceSummary\",v.created_at as \"createdAt\",v.created_by as \"createdBy\",v.version from merchant_fact_versions v where v.tenant_id=? and v.fact_id=? order by v.created_at desc",i.tenantId(),factId);}
  @Transactional public Map<String,Object> createFact(Identity i,UUID merchantId,FactInput in){
    merchant(i,merchantId); validateType(in.factScope(),in.factType()); UUID brandId=in.brandId()==null?uuid(primaryBrand(i,merchantId).get("id")):in.brandId(); requireBrand(i,merchantId,brandId); UUID storeId=in.storefrontId(); if("STOREFRONT".equals(in.factScope())){if(storeId==null)throw bad("STOREFRONT_REQUIRED","门店事实必须指定门店");requireStorefront(i,merchantId,storeId);} else if(storeId!=null)throw bad("INVALID_SCOPE","品牌事实不能绑定门店");
    UUID factId=UUID.randomUUID(),versionId=UUID.randomUUID(); OffsetDateTime now=OffsetDateTime.now(); String key=blank(in.factKey())?UUID.randomUUID().toString():in.factKey().trim();
    try {jdbc.update("insert into merchant_facts (id,tenant_id,merchant_id,brand_id,storefront_id,fact_scope,fact_type,fact_key,current_version_id,deleted,created_at,updated_at,created_by,updated_by,version) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",factId,i.tenantId(),merchantId,brandId,storeId,in.factScope(),in.factType(),key,null,false,now,now,i.userId(),i.userId(),0L); insertVersion(i,versionId,factId,merchantId,brandId,storeId,in.factType(),in.valueJson(),in.normalizedText(),in.status(),in.effectiveFrom(),in.effectiveTo(),in.verificationNotes(),in.sourceSummary(),now); jdbc.update("update merchant_facts set current_version_id=? where id=? and tenant_id=?",versionId,factId,i.tenantId());}
    catch(org.springframework.dao.DuplicateKeyException e){throw bad("FACT_KEY_EXISTS","同一事实类型和标识已存在，请使用不同事实标识或创建新版本");}
    audit.log(i.tenantId(),i.userId(),"FACT_CREATED","MerchantFact",factId,"新建 "+in.factType()+" 事实");return fact(i,merchantId,factId);
  }
  @Transactional public Map<String,Object> createVersion(Identity i,UUID merchantId,UUID factId,VersionInput in,String action){
    Map<String,Object> old=factRow(i,merchantId,factId);if(((Number)old.get("version")).longValue()!=in.expectedVersion())throw conflict(); UUID v=UUID.randomUUID(); OffsetDateTime now=OffsetDateTime.now();
    insertVersion(i,v,factId,merchantId,uuid(old.get("brandId")),uuidOrNull(old.get("storefrontId")),String.valueOf(old.get("factType")),in.valueJson(),in.normalizedText(),in.status(),in.effectiveFrom(),in.effectiveTo(),in.verificationNotes(),in.sourceSummary(),now);
    int changed=jdbc.update("update merchant_facts set current_version_id=?,updated_at=?,updated_by=?,version=version+1 where id=? and tenant_id=? and merchant_id=? and version=? and not deleted",v,now,i.userId(),factId,i.tenantId(),merchantId,in.expectedVersion());if(changed!=1)throw conflict(); audit.log(i.tenantId(),i.userId(),action,"MerchantFact",factId,"新建事实版本，状态："+in.status());return fact(i,merchantId,factId);
  }
  public Map<String,Object> verify(Identity i,UUID m,UUID f,StatusInput in){return transition(i,m,f,in,"VERIFIED","FACT_VERIFIED");} public Map<String,Object> expire(Identity i,UUID m,UUID f,StatusInput in){return transition(i,m,f,in,"EXPIRED","FACT_EXPIRED");} public Map<String,Object> dispute(Identity i,UUID m,UUID f,StatusInput in){return transition(i,m,f,in,"DISPUTED","FACT_DISPUTED");}
  private Map<String,Object> transition(Identity i,UUID m,UUID f,StatusInput in,String status,String action){Map<String,Object> old=factRow(i,m,f);return createVersion(i,m,f,new VersionInput(text(old.get("valueJson")),String.valueOf(old.get("normalizedText")),status,in.effectiveFrom(),in.effectiveTo(),in.notes(),String.valueOf(old.get("sourceSummary")),in.expectedVersion()),action);}
  @Transactional public Map<String,Object> linkEvidence(Identity i,UUID merchantId,UUID factId,EvidenceLinkInput in){
    Map<String,Object> fact=factRow(i,merchantId,factId);if(in.evidenceObservationId()==null&&in.assetId()==null&&blank(in.externalUrl()))throw bad("EVIDENCE_REQUIRED","至少绑定观察证据、附件或外部链接之一");
    if(in.evidenceObservationId()!=null)one("select id from evidence_observations where id=? and tenant_id=? and merchant_id=?",in.evidenceObservationId(),i.tenantId(),merchantId);if(in.assetId()!=null)one("select id from assets where id=? and tenant_id=?",in.assetId(),i.tenantId());
    UUID id=UUID.randomUUID();jdbc.update("insert into merchant_fact_evidence_links (id,tenant_id,fact_version_id,evidence_observation_id,asset_id,external_url,evidence_type,notes,created_at,created_by) values (?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),uuid(fact.get("currentVersionId")),in.evidenceObservationId(),in.assetId(),blank(in.externalUrl())?null:in.externalUrl(),in.evidenceType(),safe(in.notes()),OffsetDateTime.now(),i.userId());audit.log(i.tenantId(),i.userId(),"FACT_EVIDENCE_LINKED","MerchantFact",factId,"绑定事实证据");return one("select id,fact_version_id as \"factVersionId\",evidence_observation_id as \"evidenceObservationId\",asset_id as \"assetId\",external_url as \"externalUrl\",evidence_type as \"evidenceType\",notes,created_at as \"createdAt\" from merchant_fact_evidence_links where id=? and tenant_id=?",id,i.tenantId());
  }
  @Transactional public void unlinkEvidence(Identity i,UUID merchantId,UUID factId,UUID linkId){factRow(i,merchantId,factId);int n=jdbc.update("delete from merchant_fact_evidence_links l using merchant_fact_versions v where l.id=? and l.tenant_id=? and l.fact_version_id=v.id and v.fact_id=?",linkId,i.tenantId(),factId);if(n!=1)throw new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","证据关联不存在或无权访问");audit.log(i.tenantId(),i.userId(),"FACT_EVIDENCE_UNLINKED","MerchantFact",factId,"解绑事实证据");}
  private Map<String,Object> factRow(Identity i,UUID merchantId,UUID factId){return one("select f.id,f.brand_id as \"brandId\",f.storefront_id as \"storefrontId\",f.fact_scope as \"factScope\",f.fact_type as \"factType\",f.fact_key as \"factKey\",f.current_version_id as \"currentVersionId\",f.version,v.value_json::text as \"valueJson\",v.normalized_text as \"normalizedText\",v.status,v.effective_from as \"effectiveFrom\",v.effective_to as \"effectiveTo\",v.verification_notes as \"verificationNotes\",v.source_summary as \"sourceSummary\",v.created_at as \"versionCreatedAt\" from merchant_facts f join merchant_fact_versions v on v.id=f.current_version_id and v.tenant_id=f.tenant_id where f.id=? and f.tenant_id=? and f.merchant_id=? and not f.deleted",factId,i.tenantId(),merchantId);}
  private List<Map<String,Object>> links(Identity i,UUID factId,UUID versionId){return jdbc.queryForList("select l.id,l.fact_version_id as \"factVersionId\",l.evidence_observation_id as \"evidenceObservationId\",l.asset_id as \"assetId\",a.original_filename as \"assetFilename\",l.external_url as \"externalUrl\",l.evidence_type as \"evidenceType\",l.notes,l.created_at as \"createdAt\" from merchant_fact_evidence_links l left join assets a on a.id=l.asset_id and a.tenant_id=l.tenant_id join merchant_fact_versions v on v.id=l.fact_version_id and v.tenant_id=l.tenant_id where l.tenant_id=? and v.fact_id=? and l.fact_version_id=? order by l.created_at desc",i.tenantId(),factId,versionId);}
  private void insertVersion(Identity i,UUID id,UUID factId,UUID merchantId,UUID brandId,UUID storeId,String type,Object value,String normalized,String status,OffsetDateTime from,OffsetDateTime to,String notes,String source,OffsetDateTime now){if(!STATES.contains(status))throw bad("INVALID_FACT_STATUS","不支持的事实状态");if(from!=null&&to!=null&&to.isBefore(from))throw bad("INVALID_EFFECTIVE_PERIOD","有效期结束时间不能早于开始时间");jdbc.update("insert into merchant_fact_versions (id,tenant_id,fact_id,merchant_id,brand_id,storefront_id,fact_type,value_json,normalized_text,status,effective_from,effective_to,verification_notes,source_summary,created_at,created_by,version) values (?,?,?,?,?,?,?,?::jsonb,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),factId,merchantId,brandId,storeId,type,toJson(value),safe(normalized),status,from,to,safe(notes),safe(source),now,i.userId(),0L);}
  private Map<String,Object> storefront(Identity i,UUID merchantId,UUID id){return one("select id,brand_id as \"brandId\",name,is_primary as \"isPrimary\",version,created_at as \"createdAt\",updated_at as \"updatedAt\" from storefronts where id=? and tenant_id=? and merchant_id=? and not deleted",id,i.tenantId(),merchantId);}
  private void merchant(Identity i,UUID id){one("select id from merchants where id=? and tenant_id=? and not deleted",id,i.tenantId());} private void requireBrand(Identity i,UUID m,UUID id){one("select id from brand_profiles where id=? and tenant_id=? and merchant_id=? and not deleted",id,i.tenantId(),m);} private void requireStorefront(Identity i,UUID m,UUID id){one("select id from storefronts where id=? and tenant_id=? and merchant_id=? and not deleted",id,i.tenantId(),m);}
  private void validateType(String scope,String type){if(!SCOPES.contains(scope)||(scope.equals("BRAND")?!BRAND_TYPES.contains(type):!STOREFRONT_TYPES.contains(type)))throw bad("INVALID_FACT_TYPE","事实类型与作用域不匹配");} private Map<String,Object> one(String sql,Object...args){var rows=jdbc.queryForList(sql,args);if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","数据不存在或无权访问");return new LinkedHashMap<>(rows.getFirst());} private ApiException bad(String code,String msg){return new ApiException(HttpStatus.BAD_REQUEST,code,msg);}private ApiException conflict(){return new ApiException(HttpStatus.CONFLICT,"OPTIMISTIC_LOCK_CONFLICT","数据已被其他操作更新，请刷新后重试");}
  private String toJson(Object value){try{return value instanceof String s?s:json.writeValueAsString(value);}catch(JsonProcessingException e){throw bad("INVALID_FACT_VALUE","事实值无法转换为 JSON");}} private String text(Object x){return x==null?"{}":String.valueOf(x);}private UUID uuid(Object x){return UUID.fromString(String.valueOf(x));}private UUID uuidOrNull(Object x){return x==null?null:uuid(x);}private boolean blank(String s){return s==null||s.isBlank();}private String safe(String s){return s==null?"":s;}
  public record StorefrontInput(UUID brandId,String name,boolean primary){} public record StorefrontUpdate(String name,boolean primary,long expectedVersion){} public record FactInput(UUID brandId,UUID storefrontId,String factScope,String factType,String factKey,Object valueJson,String normalizedText,String status,OffsetDateTime effectiveFrom,OffsetDateTime effectiveTo,String verificationNotes,String sourceSummary){} public record VersionInput(Object valueJson,String normalizedText,String status,OffsetDateTime effectiveFrom,OffsetDateTime effectiveTo,String verificationNotes,String sourceSummary,long expectedVersion){} public record StatusInput(long expectedVersion,OffsetDateTime effectiveFrom,OffsetDateTime effectiveTo,String notes){} public record EvidenceLinkInput(UUID evidenceObservationId,UUID assetId,String externalUrl,String evidenceType,String notes){}
}
