package com.mengwei.localgrowth.platform;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mengwei.localgrowth.identity.AuthService.Identity;
import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;

@Service public class PlatformAssetService {
  private final JdbcTemplate db; private final NamedParameterJdbcTemplate named; private final ObjectMapper json;
  private static final Set<String> PLATFORMS=Set.of("XIAOHONGSHU","DIANPING","AMAP");
  private static final Set<String> FIELDS=Set.of("BRAND_NAME","STORE_NAME","ADDRESS","PHONE","BUSINESS_HOURS","SERVICE_ITEM","PRICE_RANGE");
  public PlatformAssetService(JdbcTemplate db,NamedParameterJdbcTemplate named,ObjectMapper json){this.db=db;this.named=named;this.json=json;}
  public List<Map<String,Object>> profiles(Identity i,UUID merchant){merchant(i,merchant);return db.queryForList("select * from platform_profiles where tenant_id=? and merchant_id=? and not deleted order by platform",i.tenantId(),merchant);}
  public Map<String,Object> profile(Identity i,UUID merchant,UUID id){merchant(i,merchant);return one("select * from platform_profiles where id=? and tenant_id=? and merchant_id=? and not deleted",id,i.tenantId(),merchant);}
  public Map<String,Object> createProfile(Identity i,UUID merchant,Map<String,Object> x){merchant(i,merchant);String platform=text(x,"platform");if(!PLATFORMS.contains(platform))throw bad("platform","不支持的平台");String scope=String.valueOf(x.getOrDefault("profileScope",platform.equals("XIAOHONGSHU")?"BRAND":"STOREFRONT"));UUID store=uuid(x.get("storefrontId"));if((platform.equals("DIANPING")||platform.equals("AMAP"))&&store==null)throw bad("storefrontId","该平台必须关联门店");if(store!=null&&db.queryForList("select id from storefronts where id=? and tenant_id=? and merchant_id=? and not deleted",store,i.tenantId(),merchant).isEmpty())throw bad("storefrontId","门店不存在或无权访问");UUID brand=(UUID)one("select id from brand_profiles where tenant_id=? and merchant_id=? and is_primary and not deleted",i.tenantId(),merchant).get("id");UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();MapSqlParameterSource p=new MapSqlParameterSource().addValue("id",id).addValue("tenantId",i.tenantId()).addValue("merchantId",merchant).addValue("brandId",brand).addValue("storefrontId",store).addValue("platform",platform).addValue("profileScope",scope).addValue("accountName",x.get("accountName")).addValue("profileUrl",x.get("profileUrl")).addValue("externalId",x.get("externalId")).addValue("notes",x.get("notes")).addValue("now",now).addValue("userId",i.userId());named.update("insert into platform_profiles(id,tenant_id,merchant_id,brand_id,storefront_id,platform,profile_scope,account_name,profile_url,external_id,verification_status,notes,deleted,created_at,updated_at,created_by,updated_by,version) values(:id,:tenantId,:merchantId,:brandId,:storefrontId,:platform,:profileScope,:accountName,:profileUrl,:externalId,'UNVERIFIED',:notes,false,:now,:now,:userId,:userId,0)",p);return profile(i,merchant,id);}
  public Map<String,Object> addField(Identity i,UUID merchant,UUID profileId,Map<String,Object>x){profile(i,merchant,profileId);String key=text(x,"fieldKey");if(!FIELDS.contains(key))throw bad("fieldKey","不支持的平台字段");String value=x.containsKey("value")?String.valueOf(x.get("value")):String.valueOf(x.getOrDefault("valueJson",""));if(value.isBlank())throw bad("value","平台字段值不能为空");String status=String.valueOf(x.getOrDefault("status","UNVERIFIED"));if(!Set.of("UNVERIFIED","VERIFIED","DISPUTED","OUTDATED").contains(status))throw bad("status","平台字段状态不合法");String source=String.valueOf(x.getOrDefault("sourceType","MANUAL_ENTRY"));if(!Set.of("MANUAL_ENTRY","SCREENSHOT","EXTERNAL_LINK").contains(source))throw bad("sourceType","平台字段来源不合法");Integer v=db.queryForObject("select coalesce(max(version_no),0)+1 from platform_profile_fields where tenant_id=? and profile_id=? and field_key=?",Integer.class,i.tenantId(),profileId,key);db.update("update platform_profile_fields set is_current=false where tenant_id=? and profile_id=? and field_key=? and is_current",i.tenantId(),profileId,key);UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();MapSqlParameterSource p=new MapSqlParameterSource().addValue("id",id).addValue("tenantId",i.tenantId()).addValue("merchantId",merchant).addValue("profileId",profileId).addValue("fieldKey",key).addValue("itemKey",x.get("itemKey")).addValue("fieldGroupKey",x.get("fieldGroupKey")).addValue("versionNo",v).addValue("valueJson",json(Map.of("value",value))).addValue("normalizedText",norm(value)).addValue("sourceType",source).addValue("externalUrl",x.get("externalUrl")).addValue("observedAt",time(x.get("observedAt"),now)).addValue("verifiedAt","VERIFIED".equals(status)?time(x.get("verifiedAt"),now):null).addValue("status",status).addValue("createdAt",now).addValue("createdBy",i.userId());named.update("insert into platform_profile_fields(id,tenant_id,merchant_id,profile_id,field_key,item_key,field_group_key,version_no,is_current,value_json,normalized_text,source_type,external_url,observed_at,verified_at,status,created_at,created_by,version) values(:id,:tenantId,:merchantId,:profileId,:fieldKey,:itemKey,:fieldGroupKey,:versionNo,true,cast(:valueJson as jsonb),:normalizedText,:sourceType,:externalUrl,:observedAt,:verifiedAt,:status,:createdAt,:createdBy,0)",p);return one("select * from platform_profile_fields where id=? and tenant_id=?",id,i.tenantId());}
  public List<Map<String,Object>> fields(Identity i,UUID merchant,UUID profile){profile(i,merchant,profile);return db.queryForList("select * from platform_profile_fields where tenant_id=? and profile_id=? order by field_key,version_no desc",i.tenantId(),profile);}
  public Map<String,Object> compare(Identity i,UUID merchant,UUID profileId){Map<String,Object> p=profile(i,merchant,profileId);UUID store=(UUID)p.get("storefront_id");List<Map<String,Object>> facts=db.queryForList("select f.id fact_id,f.fact_type,f.fact_key,f.fact_scope,f.storefront_id,v.id fact_version_id,v.normalized_text from merchant_facts f join merchant_fact_versions v on v.id=f.current_version_id and v.tenant_id=f.tenant_id where f.tenant_id=? and f.merchant_id=? and not f.deleted and v.status='VERIFIED' and (v.effective_from is null or v.effective_from<=now()) and (v.effective_to is null or v.effective_to>=now()) and (f.fact_scope='BRAND' or f.storefront_id=?) and f.fact_type in ('BRAND_NAME','STORE_NAME','ADDRESS','PHONE','BUSINESS_HOURS','SERVICE_ITEM','PRICE_RANGE')",i.tenantId(),merchant,store);List<Map<String,Object>> fields=db.queryForList("select * from platform_profile_fields where tenant_id=? and profile_id=? and is_current",i.tenantId(),profileId);Map<String,List<Map<String,Object>>> byKey=new HashMap<>();for(Map<String,Object>x:fields)byKey.computeIfAbsent(String.valueOf(x.get("field_key")),k->new ArrayList<>()).add(x);int created=0;for(Map<String,Object> fact:facts){String key=String.valueOf(fact.get("fact_type"));List<Map<String,Object>> candidates=byKey.getOrDefault(key,List.of());if(candidates.isEmpty()){created+=gap(i,merchant,profileId,null,fact,"MISSING_FIELD","平台未录入该事实字段");continue;}boolean matched=false;for(Map<String,Object> field:candidates){String type=null;if(!"VERIFIED".equals(field.get("status")))type="UNVERIFIED_VALUE";else if(!same(String.valueOf(field.get("normalized_text")),String.valueOf(fact.get("normalized_text"))))type=historical(i,merchant,fact,String.valueOf(field.get("normalized_text")))?"OUTDATED_VALUE":"VALUE_CONFLICT";else matched=true;if(type!=null)created+=gap(i,merchant,profileId,field,fact,type,type.equals("OUTDATED_VALUE")?"平台仍在使用该事实的历史版本":"平台资料与当前事实不一致");}if(!matched&&key.equals("SERVICE_ITEM")){/* each platform value is a service item; absence is handled above */}}
    db.update("update platform_asset_gaps set status='RESOLVED',resolved_at=?,updated_at=? where tenant_id=? and platform_profile_id=? and status='OPEN' and not exists (select 1 from platform_profile_fields pf where pf.id=platform_asset_gaps.platform_field_id and pf.is_current)",OffsetDateTime.now(),OffsetDateTime.now(),i.tenantId(),profileId);return Map.of("created",created,"gaps",gaps(i,merchant));}
  private int gap(Identity i,UUID merchant,UUID profile,Map<String,Object> field,Map<String,Object> fact,String type,String summary){UUID fieldId=field==null?null:(UUID)field.get("id");String key=String.valueOf(fact.get("fact_type"));long n=db.queryForObject("select count(*) from platform_asset_gaps where tenant_id=? and platform_profile_id=? and field_key=? and gap_type=? and status='OPEN' and ((platform_field_id is null and ?::uuid is null) or platform_field_id=?)",Long.class,i.tenantId(),profile,key,type,fieldId,fieldId);OffsetDateTime now=OffsetDateTime.now();if(n>0){db.update("update platform_asset_gaps set last_detected_at=?,updated_at=? where tenant_id=? and platform_profile_id=? and field_key=? and gap_type=? and status='OPEN'",now,now,i.tenantId(),profile,key,type);return 0;}UUID id=UUID.randomUUID();MapSqlParameterSource p=new MapSqlParameterSource().addValue("id",id).addValue("tenantId",i.tenantId()).addValue("merchantId",merchant).addValue("profileId",profile).addValue("fieldId",fieldId).addValue("factId",fact.get("fact_id")).addValue("factVersionId",fact.get("fact_version_id")).addValue("gapType",type).addValue("fieldKey",key).addValue("platformValueSnapshot",json(field==null?Map.of():Map.of("value",field.get("normalized_text")))).addValue("factValueSnapshot",json(Map.of("value",fact.get("normalized_text")))).addValue("differenceSummary",summary).addValue("now",now).addValue("userId",i.userId());named.update("insert into platform_asset_gaps(id,tenant_id,merchant_id,platform_profile_id,platform_field_id,fact_id,fact_version_id,gap_type,field_key,platform_value_snapshot,fact_value_snapshot,difference_summary,priority,status,first_detected_at,last_detected_at,created_at,updated_at,created_by,updated_by,version) values(:id,:tenantId,:merchantId,:profileId,:fieldId,:factId,:factVersionId,:gapType,:fieldKey,cast(:platformValueSnapshot as jsonb),cast(:factValueSnapshot as jsonb),:differenceSummary,'HIGH','OPEN',:now,:now,:now,:now,:userId,:userId,0)",p);return 1;}
  private boolean historical(Identity i,UUID merchant,Map<String,Object> fact,String value){Long n=db.queryForObject("select count(*) from merchant_fact_versions v join merchant_facts f on f.id=v.fact_id where f.tenant_id=? and f.merchant_id=? and f.id=? and v.id<>? and v.status='VERIFIED' and lower(regexp_replace(v.normalized_text,'[[:space:]，。,:：()\\-]','','g'))=lower(regexp_replace(?,'[[:space:]，。,:：()\\-]','','g'))",Long.class,i.tenantId(),merchant,fact.get("fact_id"),fact.get("fact_version_id"),value);return n>0;}
  public List<Map<String,Object>> gaps(Identity i,UUID merchant){merchant(i,merchant);return db.queryForList("select g.*,p.platform from platform_asset_gaps g join platform_profiles p on p.id=g.platform_profile_id and p.tenant_id=g.tenant_id where g.tenant_id=? and g.merchant_id=? order by g.status,g.created_at",i.tenantId(),merchant);}
  public Map<String,Object> resolve(Identity i,UUID merchant,UUID id,String status){merchant(i,merchant);if(!Set.of("RESOLVED","IGNORED","OPEN").contains(status))throw bad("status","Gap状态不合法");db.update("update platform_asset_gaps set status=?,resolved_at=?,updated_at=? where id=? and tenant_id=? and merchant_id=?",status,"RESOLVED".equals(status)?OffsetDateTime.now():null,OffsetDateTime.now(),id,i.tenantId(),merchant);return one("select * from platform_asset_gaps where id=? and tenant_id=?",id,i.tenantId());}
  private void merchant(Identity i,UUID id){if(db.queryForList("select id from merchants where id=? and tenant_id=? and not deleted",id,i.tenantId()).isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","商家不存在或无权访问");}
  private Map<String,Object> one(String sql,Object...args){var r=db.queryForList(sql,args);if(r.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","数据不存在或无权访问");return r.getFirst();}private String text(Map<String,Object>x,String k){Object v=x.get(k);if(v==null||String.valueOf(v).isBlank())throw bad(k,"必填字段不能为空");return String.valueOf(v);}private UUID uuid(Object v){return v==null||String.valueOf(v).isBlank()?null:UUID.fromString(String.valueOf(v));}private OffsetDateTime time(Object v,OffsetDateTime fallback){try{return v==null?fallback:OffsetDateTime.parse(String.valueOf(v));}catch(Exception e){throw bad("observedAt","日期必须为ISO-8601格式");}}private boolean same(String a,String b){return norm(a).equals(norm(b));}private String norm(String s){return s==null?"":s.toLowerCase(Locale.ROOT).replaceAll("[\\s，。,:：()\\-]","");}private String json(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalStateException(e);}}private ApiException bad(String field,String message){return new ApiException(HttpStatus.BAD_REQUEST,"PLATFORM_FIELD_INVALID",field+": "+message);}
}
