package com.mengwei.localgrowth.contentexecution;
import com.mengwei.localgrowth.identity.AuthService.Identity;import com.mengwei.localgrowth.shared.TenantAccess;import jakarta.validation.Valid;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/merchants/{merchantId}/content-execution") public class ContentExecutionController{
 private final ContentExecutionService s;private final M61DraftService drafts;private final TenantAccess a;public ContentExecutionController(ContentExecutionService s,M61DraftService d,TenantAccess a){this.s=s;drafts=d;this.a=a;}private Identity i(String h){return a.identity(h);}
 @GetMapping("/plans") List<Map<String,Object>> plans(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId){return s.plans(i(h),merchantId);} @PostMapping("/plans") Map<String,Object> createPlan(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@RequestBody ContentExecutionService.PlanInput x){return s.createPlan(i(h),merchantId,x);}@GetMapping("/plans/{id}") Map<String,Object> plan(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID id){return s.plan(i(h),merchantId,id);}@PutMapping("/plans/{id}") Map<String,Object> updatePlan(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID id,@RequestBody ContentExecutionService.PlanInput x){return s.updatePlan(i(h),merchantId,id,x);}
 @GetMapping("/plans/{planId}/work-items") List<Map<String,Object>> works(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID planId){return s.workItems(i(h),merchantId,planId);}@PostMapping("/plans/{planId}/work-items") Map<String,Object> createWork(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID planId,@RequestBody ContentExecutionService.WorkInput x){return s.createWork(i(h),merchantId,planId,x);}@PutMapping("/work-items/{id}") Map<String,Object> updateWork(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID id,@RequestBody ContentExecutionService.WorkInput x){return s.updateWork(i(h),merchantId,id,x);}
 @GetMapping("/work-items/{workId}/briefs") List<Map<String,Object>> briefs(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID workId){return s.briefs(i(h),merchantId,workId);}@PostMapping("/work-items/{workId}/briefs") Map<String,Object> createBrief(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID workId,@RequestBody ContentExecutionService.BriefInput x){return s.createBrief(i(h),merchantId,workId,x);}@PutMapping("/briefs/{id}") Map<String,Object> updateBrief(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID id,@RequestBody ContentExecutionService.BriefInput x){return s.updateBrief(i(h),merchantId,id,x);}
 @PostMapping("/briefs/{briefId}/drafts") Map<String,Object> generate(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID briefId,@RequestBody DraftInput x){return drafts.generate(i(h),merchantId,briefId,x.idempotencyKey());}@GetMapping("/briefs/{briefId}/drafts") List<Map<String,Object>> listDrafts(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID briefId){return drafts.drafts(i(h),merchantId,briefId);}@GetMapping("/drafts/{id}") Map<String,Object> draft(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID id){return drafts.draft(i(h),merchantId,id);}@PostMapping("/drafts/{id}/review") Map<String,Object> review(@RequestHeader("Authorization")String h,@PathVariable UUID merchantId,@PathVariable UUID id,@RequestBody ReviewInput x){return drafts.review(i(h),merchantId,id,x.action(),x.comment());}
 public record DraftInput(String idempotencyKey){} public record ReviewInput(String action,String comment){}
}
