package com.mengwei.localgrowth.contentexecution;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.mengwei.localgrowth.audit.AuditService;import com.mengwei.localgrowth.identity.AuthService.Identity;import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.namedparam.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service public class ContentExecutionService {
  private static final Set<String> PLAN=Set.of("DRAFT","ACTIVE","COMPLETED","CANCELLED"), WORK=Set.of("PLANNED","IN_PROGRESS","REVIEW_PENDING","APPROVED","COMPLETED","BLOCKED","CANCELLED","SUPERSEDED"), BRIEF=Set.of("BRIEF_DRAFT","BRIEF_CONFIRMED","SUPERSEDED");
  private final NamedParameterJdbcTemplate db;private final ObjectMapper json;private final AuditService audit;
  public ContentExecutionService(NamedParameterJdbcTemplate db,ObjectMapper json,AuditService audit){this.db=db;this.json=json;this.audit=audit;}
  public List<Map<String,Object>> plans(Identity i,UUID m){merchant(i,m);return db.queryForList("select * from geo_execution_plans where tenant_id=:tenantId and merchant_id=:merchantId order by created_at desc",p(i,m));}
  @Transactional public Map<String,Object> createPlan(Identity i,UUID m,PlanInput x){merchant(i,m);snapshot(i,m,x.diagnosisSnapshotId());if(x.idempotencyKey()==null||x.idempotencyKey().isBlank())throw bad("IDEMPOTENCY_KEY_REQUIRED","创建计划需要幂等键");var existing=db.queryForList("select * from geo_execution_plans where tenant_id=:tenantId and merchant_id=:merchantId and idempotency_key=:key",p(i,m).addValue("key",x.idempotencyKey()));if(!existing.isEmpty())return existing.getFirst();if(x.periodEnd().isBefore(x.periodStart()))throw bad("INVALID_PERIOD","结束日期不能早于开始日期");UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();db.update("insert into geo_execution_plans(id,tenant_id,merchant_id,diagnosis_snapshot_id,strategy_config_id,idempotency_key,name,period_start,period_end,status,executive_summary,methodology_notes,limitation_notes,created_at,updated_at,created_by,updated_by,version) values(:id,:tenantId,:merchantId,:snapshot,:strategy,:key,:name,:start,:end,:status,:summary,:method,:limits,:now,:now,:userId,:userId,0)",p(i,m).addValue("id",id).addValue("snapshot",x.diagnosisSnapshotId()).addValue("strategy",x.strategyConfigId()).addValue("key",x.idempotencyKey()).addValue("name",x.name()).addValue("start",x.periodStart()).addValue("end",x.periodEnd()).addValue("status",x.status()==null?"DRAFT":valid(x.status(),PLAN,"planStatus")).addValue("summary",x.executiveSummary()).addValue("method",x.methodologyNotes()).addValue("limits",x.limitationNotes()).addValue("now",now).addValue("userId",i.userId()));audit.log(i.tenantId(),i.userId(),"M6_PLAN_CREATED","GeoExecutionPlan",id,"创建30天执行计划");return plan(i,m,id);}
  public Map<String,Object> plan(Identity i,UUID m,UUID id){merchant(i,m);return one("select * from geo_execution_plans where id=:id and tenant_id=:tenantId and merchant_id=:merchantId",p(i,m).addValue("id",id));}
  @Transactional public Map<String,Object> updatePlan(Identity i,UUID m,UUID id,PlanInput x){plan(i,m,id);snapshot(i,m,x.diagnosisSnapshotId());db.update("update geo_execution_plans set diagnosis_snapshot_id=:snapshot,strategy_config_id=:strategy,name=:name,period_start=:start,period_end=:end,status=:status,executive_summary=:summary,methodology_notes=:method,limitation_notes=:limits,updated_at=:now,updated_by=:userId,version=version+1 where id=:id and tenant_id=:tenantId and merchant_id=:merchantId",p(i,m).addValue("id",id).addValue("snapshot",x.diagnosisSnapshotId()).addValue("strategy",x.strategyConfigId()).addValue("name",x.name()).addValue("start",x.periodStart()).addValue("end",x.periodEnd()).addValue("status",valid(x.status(),PLAN,"planStatus")).addValue("summary",x.executiveSummary()).addValue("method",x.methodologyNotes()).addValue("limits",x.limitationNotes()).addValue("now",OffsetDateTime.now()).addValue("userId",i.userId()));return plan(i,m,id);}
  public List<Map<String,Object>> workItems(Identity i,UUID m,UUID plan){this.plan(i,m,plan);return db.queryForList("select * from geo_execution_work_items where execution_plan_id=:plan and tenant_id=:tenantId and merchant_id=:merchantId order by due_date nulls last,created_at",p(i,m).addValue("plan",plan));}
  @Transactional public Map<String,Object> createWork(Identity i,UUID m,UUID plan,WorkInput x){this.plan(i,m,plan);UUID id=UUID.randomUUID();saveWork(i,m,id,plan,x,false);audit.log(i.tenantId(),i.userId(),"M6_WORK_ITEM_CREATED","GeoExecutionWorkItem",id,"创建内容执行工作项");return work(i,m,id);}
  @Transactional public Map<String,Object> updateWork(Identity i,UUID m,UUID id,WorkInput x){Map<String,Object>w=work(i,m,id);saveWork(i,m,id,(UUID)w.get("execution_plan_id"),x,true);return work(i,m,id);}
  public Map<String,Object> work(Identity i,UUID m,UUID id){merchant(i,m);return one("select * from geo_execution_work_items where id=:id and tenant_id=:tenantId and merchant_id=:merchantId",p(i,m).addValue("id",id));}
  private void saveWork(Identity i,UUID m,UUID id,UUID plan,WorkInput x,boolean update){String sql=update?"update geo_execution_work_items set task_type=:type,title=:title,description=:description,target_platform=:platform,target_question_ids=cast(:questions as jsonb),business_value=:business,gap_severity=:gap,execution_feasibility=:feasible,evidence_confidence=:confidence,priority_score=:score,priority_level=:level,owner_name=:owner,due_date=:due,status=:status,success_criteria=cast(:criteria as jsonb),updated_at=:now,updated_by=:userId,version=version+1 where id=:id and tenant_id=:tenantId and merchant_id=:merchantId":"insert into geo_execution_work_items(id,tenant_id,merchant_id,execution_plan_id,task_type,title,description,target_platform,target_question_ids,business_value,gap_severity,execution_feasibility,evidence_confidence,priority_score,priority_level,owner_name,due_date,status,success_criteria,created_at,updated_at,created_by,updated_by,version) values(:id,:tenantId,:merchantId,:plan,:type,:title,:description,:platform,cast(:questions as jsonb),:business,:gap,:feasible,:confidence,:score,:level,:owner,:due,:status,cast(:criteria as jsonb),:now,:now,:userId,:userId,0)";double score=(x.businessValue()+x.gapSeverity()+x.executionFeasibility()+x.evidenceConfidence())/4d;db.update(sql,p(i,m).addValue("id",id).addValue("plan",plan).addValue("type",x.taskType()).addValue("title",x.title()).addValue("description",x.description()).addValue("platform",x.targetPlatform()).addValue("questions",js(x.targetQuestionIds())).addValue("business",range(x.businessValue())).addValue("gap",range(x.gapSeverity())).addValue("feasible",range(x.executionFeasibility())).addValue("confidence",range(x.evidenceConfidence())).addValue("score",score).addValue("level",score>=4?"HIGH":score>=3?"MEDIUM":"LOW").addValue("owner",x.ownerName()).addValue("due",x.dueDate()).addValue("status",valid(x.status()==null?"PLANNED":x.status(),WORK,"workStatus")).addValue("criteria",js(x.successCriteria())).addValue("now",OffsetDateTime.now()).addValue("userId",i.userId()));}
  @Transactional public Map<String,Object> createBrief(Identity i,UUID m,UUID work,BriefInput x){this.work(i,m,work);int v=db.queryForObject("select coalesce(max(version),0)+1 from geo_content_briefs where work_item_id=:work",new MapSqlParameterSource("work",work),Integer.class);return saveBrief(i,m,UUID.randomUUID(),work,v,x);}
  @Transactional public Map<String,Object> updateBrief(Identity i,UUID m,UUID brief,BriefInput x){Map<String,Object> old=brief(i,m,brief);db.update("update geo_content_briefs set status='SUPERSEDED',updated_at=:now,updated_by=:user where id=:id and tenant_id=:tenant and merchant_id=:merchant",new MapSqlParameterSource().addValue("now",OffsetDateTime.now()).addValue("user",i.userId()).addValue("id",brief).addValue("tenant",i.tenantId()).addValue("merchant",m));return saveBrief(i,m,UUID.randomUUID(),(UUID)old.get("work_item_id"),((Number)old.get("version")).intValue()+1,x);}
  private Map<String,Object> saveBrief(Identity i,UUID m,UUID id,UUID work,int v,BriefInput x){OffsetDateTime now=OffsetDateTime.now();db.update("insert into geo_content_briefs(id,tenant_id,merchant_id,work_item_id,version,status,content_goal,target_audience,target_platform,content_type,target_question_ids,required_fact_ids,evidence_pack,evidence_pack_hash,prohibited_claims,content_structure,call_to_action,success_criteria,retest_criteria,created_at,updated_at,created_by,updated_by,version_lock) values(:id,:tenantId,:merchantId,:work,:version,:status,:goal,:audience,:platform,:type,cast(:questions as jsonb),cast(:facts as jsonb),'[]',null,cast(:prohibited as jsonb),cast(:structure as jsonb),:cta,cast(:success as jsonb),cast(:retest as jsonb),:now,:now,:userId,:userId,0)",p(i,m).addValue("id",id).addValue("work",work).addValue("version",v).addValue("status",valid(x.status()==null?"BRIEF_DRAFT":x.status(),BRIEF,"briefStatus")).addValue("goal",x.contentGoal()).addValue("audience",x.targetAudience()).addValue("platform",x.targetPlatform()).addValue("type",x.contentType()).addValue("questions",js(x.targetQuestionIds())).addValue("facts",js(x.requiredFactIds())).addValue("prohibited",js(x.prohibitedClaims())).addValue("structure",js(x.contentStructure())).addValue("cta",x.callToAction()).addValue("success",js(x.successCriteria())).addValue("retest",js(x.retestCriteria())).addValue("now",now).addValue("userId",i.userId()));audit.log(i.tenantId(),i.userId(),"M6_BRIEF_CREATED","GeoContentBrief",id,"创建内容Brief版本 "+v);return brief(i,m,id);}
  public Map<String,Object> brief(Identity i,UUID m,UUID id){merchant(i,m);return one("select * from geo_content_briefs where id=:id and tenant_id=:tenantId and merchant_id=:merchantId",p(i,m).addValue("id",id));}
  public List<Map<String,Object>> briefs(Identity i,UUID m,UUID work){this.work(i,m,work);return db.queryForList("select * from geo_content_briefs where work_item_id=:work and tenant_id=:tenantId and merchant_id=:merchantId order by version desc",p(i,m).addValue("work",work));}
  private void merchant(Identity i,UUID m){if(db.queryForList("select id from merchants where id=:merchantId and tenant_id=:tenantId and not deleted",p(i,m)).isEmpty())throw bad("NOT_FOUND","数据不存在或无权访问");}private void snapshot(Identity i,UUID m,UUID id){if(id==null||db.queryForList("select id from geo_diagnosis_snapshots where id=:id and tenant_id=:tenantId and merchant_id=:merchantId",p(i,m).addValue("id",id)).isEmpty())throw bad("DIAGNOSIS_SNAPSHOT_NOT_FOUND","正式诊断快照不存在或无权访问");}private MapSqlParameterSource p(Identity i,UUID m){return new MapSqlParameterSource().addValue("tenantId",i.tenantId()).addValue("merchantId",m);}private Map<String,Object> one(String s,MapSqlParameterSource p){var r=db.queryForList(s,p);if(r.isEmpty())throw bad("NOT_FOUND","数据不存在或无权访问");return r.getFirst();}private String valid(String s,Set<String> allowed,String field){if(!allowed.contains(s))throw bad("INVALID_STATUS",field+" 不合法");return s;}private int range(Integer n){if(n==null||n<1||n>5)throw bad("INVALID_PRIORITY","优先级维度必须为1至5");return n;}private String js(Object x){try{return json.writeValueAsString(x==null?List.of():x);}catch(Exception e){throw new IllegalStateException(e);}}private ApiException bad(String c,String m){return new ApiException(HttpStatus.BAD_REQUEST,c,m);}
  public record PlanInput(UUID diagnosisSnapshotId,UUID strategyConfigId,String idempotencyKey,String name,LocalDate periodStart,LocalDate periodEnd,String status,String executiveSummary,String methodologyNotes,String limitationNotes){} public record WorkInput(String taskType,String title,String description,String targetPlatform,List<UUID> targetQuestionIds,Integer businessValue,Integer gapSeverity,Integer executionFeasibility,Integer evidenceConfidence,String ownerName,LocalDate dueDate,String status,Map<String,Object> successCriteria){} public record BriefInput(String status,String contentGoal,String targetAudience,String targetPlatform,String contentType,List<UUID> targetQuestionIds,List<UUID> requiredFactIds,List<String> prohibitedClaims,List<Map<String,Object>> contentStructure,String callToAction,Map<String,Object> successCriteria,Map<String,Object> retestCriteria){}
}
