package com.mengwei.localgrowth.diagnostic;
import com.mengwei.localgrowth.audit.AuditService; import com.mengwei.localgrowth.identity.AuthService.Identity; import com.mengwei.localgrowth.model.*; import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;
import java.math.BigDecimal; import java.math.RoundingMode; import java.time.OffsetDateTime; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service;
@Service public class DiagnosticService {
  private final JdbcTemplate jdbc;private final AuditService audit;private final List<ModelProviderPort> providers;
  public DiagnosticService(JdbcTemplate j,AuditService a,List<ModelProviderPort> p){jdbc=j;audit=a;providers=p;}
  public Map<String,Object> run(Identity i,UUID merchantId,String providerName){
    var merchant=one("select name,city from merchants where id=? and tenant_id=? and deleted=false",merchantId,i.tenantId());var brand=one("select name,aliases,services,claims from brands where merchant_id=? and tenant_id=? and deleted=false order by created_at limit 1",merchantId,i.tenantId());
    var prompts=jdbc.queryForList("select id,question from prompt_cases where merchant_id=? and tenant_id=? and enabled=true and deleted=false",merchantId,i.tenantId());if(prompts.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"NO_PROMPTS","请先至少添加一个启用的测试问题");
    ModelProviderPort provider=providers.stream().filter(p->p.name().equalsIgnoreCase(providerName)).findFirst().orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"PROVIDER_UNAVAILABLE","未找到指定模型提供商"));
    UUID run=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into diagnostic_runs values (?,?,?,?,?,?,?,?,?,?,?)",run,i.tenantId(),merchantId,"COMPLETED",provider.name(),"演示样本：仅用于方法验证，Mock 回答不构成真实模型观测。",now,now,i.userId(),i.userId(),0L);
    for(var p:prompts){var answer=provider.invoke((String)p.get("question"),(String)brand.get("name"),(String)brand.get("services"),(String)merchant.get("city"));jdbc.update("insert into answer_snapshots values (?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),i.tenantId(),run,p.get("id"),answer.model(),answer.text(),answer.simulated(),answer.durationMs(),now);}
    Map<String,Object> report=scoreAndReport(i,run,merchantId,brand,merchant);audit.log(i.tenantId(),i.userId(),"DIAGNOSTIC_COMPLETED","DiagnosticRun",run,"完成 "+prompts.size()+" 个问题的 "+provider.name()+" 诊断");return report;
  }
  public Map<String,Object> result(Identity i,UUID runId){var run=one("select id,merchant_id,status,provider,sample_note,created_at from diagnostic_runs where id=? and tenant_id=?",runId,i.tenantId());var report=jdbc.queryForList("select id,score,report_markdown,score_snapshot,created_at from diagnostic_reports where diagnostic_run_id=? and tenant_id=?",runId,i.tenantId());var answers=jdbc.queryForList("select a.id,p.question,a.model_name,a.response_text,a.simulated,a.duration_ms,a.created_at from answer_snapshots a join prompt_cases p on p.id=a.prompt_case_id where a.diagnostic_run_id=? and a.tenant_id=?",runId,i.tenantId());var output=new LinkedHashMap<String,Object>();output.put("run",run);output.put("answers",answers);output.put("report",report.isEmpty()?null:report.getFirst());return output;}
  private Map<String,Object> scoreAndReport(Identity i,UUID run,UUID merchantId,Map<String,Object> brand,Map<String,Object> merchant){
    var answers=jdbc.queryForList("select response_text,model_name from answer_snapshots where diagnostic_run_id=? and tenant_id=?",run,i.tenantId());var competitors=jdbc.queryForList("select name,aliases from competitors where merchant_id=? and tenant_id=? and deleted=false",merchantId,i.tenantId());List<String> aliases=terms((String)brand.get("name"),(String)brand.get("aliases")); int mentioned=0, firstTotal=0, competitorAnswers=0;List<Map<String,Object>> evidence=new ArrayList<>();
    for(var a:answers){String text=((String)a.get("response_text")).toLowerCase(Locale.ROOT);int pos=first(text,aliases);boolean hit=pos>=0;if(hit){mentioned++;firstTotal+=pos;evidence.add(Map.of("model",a.get("model_name"),"position",pos,"snippet",snippet((String)a.get("response_text"),pos)));} boolean comp=false;for(var c:competitors){if(first(text,terms((String)c.get("name"),(String)c.get("aliases")))>=0){comp=true;break;}}if(comp)competitorAnswers++;}
    int total=answers.size();double coverage=total==0?0:mentioned*100d/total;double prominence=mentioned==0?0:Math.max(0,100-(firstTotal/(double)mentioned)/3);String claims=(String)brand.get("claims");double consistency=claims==null||claims.isBlank()?0:(mentioned==0?0:70);double share=competitors.isEmpty()?0:mentioned*100d/(mentioned+competitorAnswers==0?1:mentioned+competitorAnswers);double score=coverage*.30+coverage*.20+prominence*.20+consistency*.15+share*.15;score=BigDecimal.valueOf(score).setScale(1,RoundingMode.HALF_UP).doubleValue();
    String md=reportMarkdown((String)merchant.get("name"),(String)brand.get("name"),total,mentioned,competitorAnswers,score,coverage,prominence,consistency,competitors.size());String snapshot="{\"rule\":\"GEO_SCORE_V1\",\"coverage\":"+round(coverage)+",\"modelCoverage\":"+round(coverage)+",\"prominence\":"+round(prominence)+",\"consistency\":"+round(consistency)+",\"competitiveShare\":"+round(share)+"}";UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into diagnostic_reports values (?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),run,score,md,snapshot,now,now,i.userId(),i.userId(),0L);return Map.of("runId",run,"reportId",id,"score",score,"brandMentions",mentioned,"answerCount",total,"evidence",evidence,"reportMarkdown",md,"simulated",true);
  }
  private List<String> terms(String name,String aliases){List<String> r=new ArrayList<>();r.add(name.toLowerCase(Locale.ROOT));if(aliases!=null)for(String s:aliases.split("[,，\n]"))if(!s.isBlank())r.add(s.trim().toLowerCase(Locale.ROOT));return r;}
  private int first(String t,List<String> terms){return terms.stream().mapToInt(t::indexOf).filter(x->x>=0).min().orElse(-1);} private String snippet(String s,int p){return s.substring(Math.max(0,p-30),Math.min(s.length(),p+100));}private String round(double n){return BigDecimal.valueOf(n).setScale(1,RoundingMode.HALF_UP).toString();}
  private String reportMarkdown(String merchant,String brand,int total,int mentioned,int competitors,double score,double coverage,double prominence,double consistency,int configured){return "# "+merchant+"｜AI 可见度诊断报告\n\n## 结论\n\n本次在 **"+total+"** 条回答样本中，品牌 **"+brand+"** 出现 **"+mentioned+"** 次，GEO Score 为 **"+round(score)+" / 100**。这是对本次样本的观测，不是搜索排名承诺。\n\n## 评分构成\n\n- 回答覆盖率："+round(coverage)+" / 100（权重 30%）\n- 模型覆盖率："+round(coverage)+" / 100（权重 20%，本次为单模型样本）\n- 提及显著性："+round(prominence)+" / 100（权重 20%）\n- 已验证信息一致性："+round(consistency)+" / 100（权重 15%）\n- 竞争可见度："+(configured==0?"未配置竞品，暂不比较":round(mentioned*100d/(mentioned+competitors==0?1:mentioned+competitors))+" / 100")+"（权重 15%）\n\n## 优先建议\n\n1. **补齐实体资料**：把官网、服务区域、服务项目、价格范围、真实案例与联系方式统一成可核验的品牌档案。\n2. **把高意图问题做成 FAQ**：优先覆盖本次未出现品牌的问题，逐条以真实案例、交付范围和证据回答。\n3. **建立第三方证据清单**：仅维护真实、可验证的客户案例、资质与媒体/平台资料；不要制造评论或虚假内容。\n4. **两周后复测**：使用相同问题集与模型设置，比较新的评分快照，而非承诺绝对排名。\n\n## 样本与局限\n\n- 本报告由 MockProvider 生成，供产品演示与流程验证；接入已授权的真实模型后才可形成正式观测。\n- 模型回答会随时间、版本、地域和措辞变化；小样本不应用于强因果结论。";}
  private Map<String,Object> one(String sql,Object... args){var r=jdbc.queryForList(sql,args);if(r.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"PREREQUISITE_MISSING","请先创建商家及品牌档案");return r.getFirst();}
}
