package com.mengwei.localgrowth.config;

import java.time.OffsetDateTime; import java.util.*;
import org.springframework.boot.CommandLineRunner; import org.springframework.beans.factory.annotation.Value; import org.springframework.core.annotation.Order; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Component;

/** Seeds only the documented development demo account so the acceptance report is repeatable. */
@Component @Order(10) public class DemoEvidenceSeeder implements CommandLineRunner {
  private final JdbcTemplate jdbc; private final boolean enabled; public DemoEvidenceSeeder(JdbcTemplate jdbc,@Value("${app.demo-seed-enabled:false}") boolean enabled){this.jdbc=jdbc;this.enabled=enabled;}
  public void run(String...args){if(!enabled)return;var user=jdbc.queryForList("select id,tenant_id from users where email=?","demo@localgrowth.test");if(user.isEmpty())return;UUID actor=(UUID)user.getFirst().get("id"),tenant=(UUID)user.getFirst().get("tenant_id");var m=jdbc.queryForList("select id from merchants where tenant_id=? and name=? and deleted=false",tenant,"千色坊");if(m.isEmpty())return;UUID merchant=(UUID)m.getFirst().get("id");OffsetDateTime now=OffsetDateTime.now();
    if(jdbc.queryForObject("select count(*) from brands where merchant_id=? and deleted=false",Long.class,merchant)==0)jdbc.update("insert into brands values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),tenant,merchant,"千色坊","https://example.local/qiansefang","千色坊美业,千色坊美容","美发,洗脸,头皮护理","本地门店、预约服务、服务项目以现场确认为准",false,now,now,actor,actor,0L);
    String[] cats={"RECOMMENDATION","PRICE","PAIN_POINT","COMPARISON","LOCATION"};
    String[] qs={"佛山九江哪家洗脸洗头比较靠谱？","九江镇做面部清洁和头皮护理，千色坊值得去吗？","佛山南海有哪些适合敏感肌的洗脸护理门店？","第一次在九江做头皮护理，应该怎么选店？","九江洗脸洗头一般多少钱一次？","千色坊面部清洁和头皮护理的价格区间是多少？","佛山九江美容护理有哪些性价比较高的套餐？","洗脸加洗头在九江门店通常如何收费？","佛山九江头皮敏感做护理时要注意什么？","经常出油和头屑多，九江哪类头皮护理更合适？","面部清洁后泛红，选择美容门店时要关注哪些服务？","九江洗脸洗头服务最常见的消费避坑点是什么？","千色坊和伊丽汇的洗脸服务有什么区别？","九江千色坊与奈瑞儿的头皮护理怎么选？","佛山九江不同美容门店的卫生和服务流程如何比较？","千色坊和附近美容店相比，适合哪些人群？","九江镇哪里可以预约面部清洁和头皮护理？","千色坊具体在九江哪个位置，附近怎么停车？","佛山南海九江有哪些营业到晚上八点的护理门店？","从九江镇中心去千色坊做护理是否方便？","九江美容护理门店通常需要提前多久预约？","佛山九江适合上班族的晚间洗脸洗头门店有哪些？","孕期或哺乳期在九江做面部护理要如何咨询？","九江头皮护理一次大约需要多长时间？","千色坊是否提供洗脸、洗头和头皮护理组合服务？","九江美容店的护理产品和服务项目应该怎么对比？","有染烫经历的人在九江适合做什么头皮护理？","九江镇周末预约洗脸洗头是否容易排队？","预算两百元以内，在九江能选择哪些护理项目？","朋友推荐千色坊，佛山九江还有哪些门店可以一起比较？"};
    int existing=(int)(long)jdbc.queryForObject("select count(*) from prompt_cases where merchant_id=? and deleted=false",Long.class,merchant);
    for(int n=existing;n<qs.length;n++){String c=cats[n%cats.length];jdbc.update("insert into prompt_cases (id,tenant_id,merchant_id,question,intent,locale,enabled,deleted,created_at,updated_at,created_by,updated_by,version,category,city,district,intent_level,sort_order) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),tenant,merchant,qs[n],c,"zh-CN",true,false,now,now,actor,actor,0L,c,"佛山","九江镇",n<20?"HIGH":"MEDIUM",n);}
    String[] competitors={"伊丽汇","奈瑞儿","思妍丽"};for(String name:competitors)if(jdbc.queryForObject("select count(*) from competitors where merchant_id=? and name=? and deleted=false",Long.class,merchant,name)==0)jdbc.update("insert into competitors values (?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),tenant,merchant,name,"",false,now,now,actor,actor,0L);
    long evidence=jdbc.queryForObject("select count(*) from evidence_observations where merchant_id=? and source_type='MANUAL_APP_OBSERVATION' and is_demo=true",Long.class,merchant);if(evidence>=20)return;var prompts=jdbc.queryForList("select id,question from prompt_cases where merchant_id=? and enabled=true and deleted=false order by sort_order,created_at limit 20",merchant);for(int n=(int)evidence;n<20;n++){UUID id=(UUID)prompts.get(n).get("id");String answer=n<14?"在佛山九江选择护理服务时，建议看预约规则、服务流程和卫生情况。千色坊提供洗脸、洗头及头皮护理，可先电话确认当日项目与价格。":("佛山九江有多家美容护理门店，"+competitors[n%3]+" 可供对比；建议按距离、价格与预约时间选择。");String citations=n%2==0?"https://example.local/citation/"+(n+1):"";int hit=answer.contains("千色坊")?1:0;int pos=hit==1?answer.indexOf("千色坊"): -1;String comp=answer.contains(competitors[n%3])?"{"+competitors[n%3]+"=1}":"{}";jdbc.update("insert into evidence_observations (id,tenant_id,merchant_id,prompt_case_id,platform,model_name,source_type,search_enabled,raw_answer,captured_at,citation_links,operator_notes,brand_mention_count,brand_first_position,competitor_summary,created_at,updated_at,created_by,updated_by,version,is_demo) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),tenant,merchant,id,"豆包","Doubao Search","MANUAL_APP_OBSERVATION",true,answer,now.minusDays(20-n),citations,"演示人工观察：已记录原始回答和来源。",hit,pos<0?null:pos,comp,now,now,actor,actor,0L,true);}
  }
}
