<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, apiObjectUrl } from '../../api'
import { useMerchantContext } from '../../stores/merchantContext'

const ctx=useMerchantContext(); const loading=ref(false); const summary=ref<any>({counts:{},storefronts:[]}); const facts=ref<any[]>([]); const selectedStorefront=ref<string>(''); const selectedFact=ref<any|null>(null); const history=ref<any[]>([]); const drawer=ref(false); const historyDialog=ref(false); const storeDialog=ref(false); const evidenceDialog=ref(false); const assetPreview=ref<string>('')
const factForm=ref<any>(blankFact()); const storeForm=ref<any>({name:'',primary:false,expectedVersion:0}); const evidenceForm=ref<any>({evidenceObservationId:'',assetId:'',externalUrl:'',evidenceType:'EXTERNAL_URL',notes:''});
const brandTypes=['BRAND_NAME','BRAND_ALIAS','HISTORICAL_NAME','SERVICE_ITEM','TARGET_AUDIENCE','QUALIFICATION','PROMOTABLE_CLAIM','PROHIBITED_CLAIM','CASE_STUDY','MEDIA_ASSET']; const storeTypes=['STORE_NAME','ADDRESS','GEO_LOCATION','PHONE','BUSINESS_HOURS','SERVICE_AREA','PARKING_AND_TRANSIT','PRICE_RANGE','PACKAGE','CONTACT_METHOD','CASE_STUDY','MEDIA_ASSET']; const statuses=['UNVERIFIED','VERIFIED','EXPIRED','DISPUTED']
function blankFact(){return {factScope:'BRAND',factType:'BRAND_NAME',factKey:'',valueText:'',normalizedText:'',status:'UNVERIFIED',effectiveFrom:null,effectiveTo:null,verificationNotes:'',sourceSummary:''}}
const merchantId=computed(()=>ctx.merchant.value?.id); const activeFacts=computed(()=>facts.value.filter(f=>!selectedStorefront.value||f.factScope==='BRAND'||f.storefrontId===selectedStorefront.value)); const availableTypes=computed(()=>factForm.value.factScope==='BRAND'?brandTypes:storeTypes)
const statusType=(s:string)=>s==='VERIFIED'?'success':s==='EXPIRED'?'info':s==='DISPUTED'?'danger':'warning'
const label=(v:string)=>({BRAND_NAME:'品牌名称',BRAND_ALIAS:'品牌别名',HISTORICAL_NAME:'历史名称',SERVICE_ITEM:'服务项目',TARGET_AUDIENCE:'适用人群',QUALIFICATION:'资质',PROMOTABLE_CLAIM:'可宣传事实',PROHIBITED_CLAIM:'禁止宣传事项',STORE_NAME:'门店名称',ADDRESS:'地址',GEO_LOCATION:'经纬度',PHONE:'电话',BUSINESS_HOURS:'营业时间',SERVICE_AREA:'服务区域',PARKING_AND_TRANSIT:'停车和交通',PRICE_RANGE:'价格区间',PACKAGE:'套餐',CONTACT_METHOD:'联系方式'} as any)[v]||v
function parse(v:any){try{return typeof v==='string'?JSON.parse(v):v}catch{return v}}
function valueText(v:any){const x=parse(v);return typeof x==='string'?x:JSON.stringify(x, null, 2)}
async function load(){if(!merchantId.value)return; loading.value=true;try{const q=selectedStorefront.value?`?storefrontId=${selectedStorefront.value}`:'';[summary.value,facts.value]=await Promise.all([api(`/merchants/${merchantId.value}/fact-center/summary`),api(`/merchants/${merchantId.value}/facts${q}`)]);if(!selectedStorefront.value){selectedStorefront.value=summary.value.storefronts?.find((s:any)=>s.isPrimary)?.id||''}}catch(e:any){ElMessage.error(e.message)}finally{loading.value=false}}
watch(merchantId,()=>{selectedStorefront.value='';selectedFact.value=null;load()},{immediate:true});watch(selectedStorefront,()=>merchantId.value&&load())
function openCreate(){factForm.value=blankFact(); factForm.value.storefrontId=selectedStorefront.value||undefined; drawer.value=true}
function openVersion(f:any){selectedFact.value=f;factForm.value={...blankFact(),factScope:f.factScope,factType:f.factType,factKey:f.factKey,valueText:valueText(f.valueJson),normalizedText:f.normalizedText,status:f.status,effectiveFrom:f.effectiveFrom,effectiveTo:f.effectiveTo,verificationNotes:f.verificationNotes,sourceSummary:f.sourceSummary,expectedVersion:f.version};drawer.value=true}
function payload(){let valueJson:any;try{valueJson=JSON.parse(factForm.value.valueText)}catch{valueJson={text:factForm.value.valueText}}return {...factForm.value,valueJson,storefrontId:factForm.value.factScope==='STOREFRONT'?(factForm.value.storefrontId||selectedStorefront.value):null}}
async function saveFact(){try{if(!factForm.value.normalizedText||!factForm.value.valueText){ElMessage.warning('请填写结构化事实值和标准展示文本');return} const p=payload();if(selectedFact.value) await api(`/merchants/${merchantId.value}/facts/${selectedFact.value.id}/versions`,{method:'POST',body:JSON.stringify(p)});else await api(`/merchants/${merchantId.value}/facts`,{method:'POST',body:JSON.stringify(p)});ElMessage.success(selectedFact.value?'已创建新版本':'事实已建立');drawer.value=false;selectedFact.value=null;await load()}catch(e:any){ElMessage.error(e.message)}}
async function transition(f:any,action:'verify'|'expire'|'dispute'){try{await api(`/merchants/${merchantId.value}/facts/${f.id}/${action}`,{method:'POST',body:JSON.stringify({expectedVersion:f.version,notes:action==='verify'?'运营人工核验':action==='expire'?'运营标记过期':'运营标记争议'})});ElMessage.success('状态已更新，原版本仍保留');await load()}catch(e:any){ElMessage.error(e.message)}}
async function showHistory(f:any){try{selectedFact.value=await api(`/merchants/${merchantId.value}/facts/${f.id}`);history.value=await api(`/merchants/${merchantId.value}/facts/${f.id}/versions`);historyDialog.value=true}catch(e:any){ElMessage.error(e.message)}}
async function createStore(){try{await api(`/merchants/${merchantId.value}/storefronts`,{method:'POST',body:JSON.stringify({brandId:summary.value.brand?.id,name:storeForm.value.name,primary:storeForm.value.primary})});ElMessage.success('门店已新增');storeDialog.value=false;storeForm.value={name:'',primary:false};await load()}catch(e:any){ElMessage.error(e.message)}}
async function bindEvidence(){if(!selectedFact.value)return;try{await api(`/merchants/${merchantId.value}/facts/${selectedFact.value.id}/evidence-links`,{method:'POST',body:JSON.stringify({...evidenceForm.value,evidenceObservationId:evidenceForm.value.evidenceObservationId||null,assetId:evidenceForm.value.assetId||null})});ElMessage.success('证据已绑定到当前版本');evidenceDialog.value=false;evidenceForm.value={evidenceObservationId:'',assetId:'',externalUrl:'',evidenceType:'EXTERNAL_URL',notes:''};selectedFact.value=await api(`/merchants/${merchantId.value}/facts/${selectedFact.value.id}`);await load()}catch(e:any){ElMessage.error(e.message)}}
async function unlink(link:any){try{await ElMessageBox.confirm('解绑不会删除附件或观察证据，是否继续？','解绑证据');await api(`/merchants/${merchantId.value}/facts/${selectedFact.value.id}/evidence-links/${link.id}`,{method:'DELETE'});selectedFact.value=await api(`/merchants/${merchantId.value}/facts/${selectedFact.value.id}`);ElMessage.success('已解绑')}catch(e:any){if(e!=='cancel')ElMessage.error(e.message||'操作失败')}}
async function upload(e:any){const file=e.file;try{const form=new FormData();form.append('file',file);const a=await api('/assets',{method:'POST',body:form});evidenceForm.value.assetId=a.id;ElMessage.success('附件已上传，提交后才会绑定事实')}catch(err:any){ElMessage.error(err.message)}}
async function preview(id:string){try{if(assetPreview.value)URL.revokeObjectURL(assetPreview.value);assetPreview.value=await apiObjectUrl(`/assets/${id}/content`)}catch(e:any){ElMessage.error(e.message)}}
</script>
<template>
<section class="module-page fact-center" v-loading="loading">
  <div class="module-heading"><div><span class="eyebrow">M1 · FACT CENTER</span><h2>商家事实与实体中心</h2><p>将可宣传信息、门店资料和证据归档为可核验的结构化事实。只有标记为已核验的信息才可在下一阶段提供给真实模型。</p></div><el-button type="primary" @click="openCreate">新建事实</el-button></div>
  <div class="fact-stats"><div class="entity-card"><span>主品牌</span><b>{{summary.brand?.name||'迁移中'}}</b><small>Merchant 仍是工作台聚合根</small></div><div class="metric"><b>{{summary.counts?.currentEffective||0}}</b><span>当前有效事实</span></div><div class="metric verified"><b>{{summary.counts?.verified||0}}</b><span>已核验</span></div><div class="metric warning"><b>{{summary.counts?.unverified||0}}</b><span>待核验</span></div><div class="metric danger"><b>{{(summary.counts?.expired||0)+(summary.counts?.disputed||0)}}</b><span>过期 / 争议</span></div></div>
  <div class="fact-workspace"><aside class="fact-sidebar panel"><div class="panel-title"><h3>门店实体</h3><el-button text type="primary" @click="storeDialog=true">+ 新增门店</el-button></div><button class="store-choice" :class="{active:!selectedStorefront}" @click="selectedStorefront=''">全部事实 <small>品牌 + 门店</small></button><button v-for="s in summary.storefronts" :key="s.id" class="store-choice" :class="{active:selectedStorefront===s.id}" @click="selectedStorefront=s.id"><b>{{s.name}}</b><small>{{s.isPrimary?'主门店':'门店'}}</small></button><div class="boundary"><b>宣传边界</b><p>绿色：已核验且可用<br>黄色：未核验<br>红色：过期或争议，不应作为宣传依据</p></div></aside>
    <main class="facts-list panel"><div class="panel-title"><div><h3>{{selectedStorefront?'门店事实':'品牌与门店事实'}}</h3><small>修改事实会创建新版本，不覆盖历史。</small></div><el-button plain @click="openCreate">添加</el-button></div><div v-if="!activeFacts.length" class="empty">暂未录入事实。先添加地址、电话、营业时间、价格区间等可核验资料。</div><article v-for="f in activeFacts" :key="f.id" class="fact-row"><div class="fact-main"><div class="fact-title"><el-tag size="small" effect="plain">{{label(f.factType)}}</el-tag><el-tag size="small" :type="statusType(f.status)">{{f.status}}</el-tag><span v-if="f.factScope==='STOREFRONT'" class="scope">门店</span></div><b>{{f.normalizedText}}</b><small v-if="f.effectiveFrom||f.effectiveTo">有效期：{{f.effectiveFrom||'未设'}} 至 {{f.effectiveTo||'长期'}}</small><small v-if="f.sourceSummary">来源：{{f.sourceSummary}}</small></div><div class="fact-actions"><el-button size="small" @click="openVersion(f)">新版本</el-button><el-dropdown @command="(x:string)=>transition(f,x as any)"><el-button size="small" plain>状态</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="verify">标记已核验</el-dropdown-item><el-dropdown-item command="expire">标记过期</el-dropdown-item><el-dropdown-item command="dispute">标记争议</el-dropdown-item></el-dropdown-menu></template></el-dropdown><el-button size="small" text @click="showHistory(f)">历史</el-button></div></article></main>
  </div>
  <el-drawer v-model="drawer" :title="selectedFact?'创建事实新版本':'新建结构化事实'" size="520px"><el-form label-position="top"><el-form-item label="事实作用域"><el-radio-group v-model="factForm.factScope" :disabled="!!selectedFact"><el-radio-button label="BRAND">品牌</el-radio-button><el-radio-button label="STOREFRONT">门店</el-radio-button></el-radio-group></el-form-item><el-form-item v-if="factForm.factScope==='STOREFRONT'" label="所属门店"><el-select v-model="factForm.storefrontId" placeholder="请选择门店"><el-option v-for="s in summary.storefronts" :key="s.id" :value="s.id" :label="s.name"/></el-select></el-form-item><el-form-item label="事实类型"><el-select v-model="factForm.factType" :disabled="!!selectedFact"><el-option v-for="t in availableTypes" :key="t" :value="t" :label="label(t)"/></el-select></el-form-item><el-form-item label="事实标识（同类型重复内容请填写）"><el-input v-model="factForm.factKey" placeholder="例如：price-2026-q3；为空则自动生成" :disabled="!!selectedFact"/></el-form-item><el-form-item label="结构化事实值"><el-input v-model="factForm.valueText" type="textarea" :rows="4" placeholder='可填 JSON，例如 {"min":98,"max":198,"currency":"CNY"}'/></el-form-item><el-form-item label="标准展示文本"><el-input v-model="factForm.normalizedText" placeholder="用于事实列表、审计和人工阅读"/></el-form-item><el-form-item label="状态"><el-select v-model="factForm.status"><el-option v-for="s in statuses" :key="s" :value="s"/></el-select></el-form-item><el-form-item label="有效期"><div class="date-range"><el-date-picker v-model="factForm.effectiveFrom" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssXXX" placeholder="开始"/><el-date-picker v-model="factForm.effectiveTo" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssXXX" placeholder="结束"/></div></el-form-item><el-form-item label="核验说明"><el-input v-model="factForm.verificationNotes" type="textarea" :rows="2"/></el-form-item><el-form-item label="来源摘要"><el-input v-model="factForm.sourceSummary" placeholder="例如：门店营业执照、官网截图、运营人工确认"/></el-form-item><el-button type="primary" @click="saveFact">{{selectedFact?'保存为新版本':'建立事实'}}</el-button></el-form></el-drawer>
  <el-dialog v-model="storeDialog" title="新增门店" width="460px"><el-form label-position="top"><el-form-item label="门店名称"><el-input v-model="storeForm.name"/></el-form-item><el-checkbox v-model="storeForm.primary">设为主门店</el-checkbox></el-form><template #footer><el-button @click="storeDialog=false">取消</el-button><el-button type="primary" @click="createStore">保存门店</el-button></template></el-dialog>
  <el-dialog v-model="historyDialog" title="事实历史版本" width="760px" @closed="history=[]"><div v-for="v in history" :key="v.id" class="history-item"><div><el-tag :type="statusType(v.status)">{{v.status}}</el-tag><b v-if="v.id===selectedFact?.currentVersionId">当前版本</b><small>{{v.createdAt}}</small></div><pre>{{valueText(v.valueJson)}}</pre><p>{{v.normalizedText}}</p><small>{{v.verificationNotes}}</small><div class="history-links" v-if="v.id===selectedFact?.currentVersionId"><el-button size="small" @click="evidenceDialog=true">绑定证据</el-button><el-button v-for="link in selectedFact?.evidenceLinks||[]" :key="link.id" size="small" plain @click="link.assetId?preview(link.assetId):undefined">{{link.assetFilename||link.externalUrl||link.evidenceType}} <span @click.stop="unlink(link)">×</span></el-button></div></div></el-dialog>
  <el-dialog v-model="evidenceDialog" title="绑定事实证据" width="520px"><el-form label-position="top"><el-form-item label="观察证据（可选）"><el-select v-model="evidenceForm.evidenceObservationId" clearable filterable placeholder="选择问题与观察中的真实回答"><el-option v-for="e in ctx.data.evidence" :key="e.id" :value="e.id" :label="`${e.platform} · ${e.question||'观察证据'} · ${e.captured_at||''}`"/></el-select></el-form-item><el-form-item label="外部链接（可选）"><el-input v-model="evidenceForm.externalUrl" placeholder="官网、资质页或公开资料链接"/></el-form-item><el-form-item label="上传附件（可选）"><el-upload :show-file-list="false" :http-request="upload" accept="image/png,image/jpeg,image/webp"><el-button>上传图片附件</el-button></el-upload><small v-if="evidenceForm.assetId">已上传附件 ID：{{evidenceForm.assetId}}</small></el-form-item><el-form-item label="证据类型"><el-select v-model="evidenceForm.evidenceType"><el-option value="EXTERNAL_URL" label="外部链接"/><el-option value="OBSERVATION" label="观察证据"/><el-option value="ASSET" label="已上传附件"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="evidenceForm.notes" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="evidenceDialog=false">取消</el-button><el-button type="primary" @click="bindEvidence">绑定当前版本</el-button></template></el-dialog>
  <el-image-viewer v-if="assetPreview" :url-list="[assetPreview]" @close="assetPreview=''"/>
</section>
</template>
<style scoped>
.fact-center{max-width:1440px}.fact-stats{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:14px;margin-bottom:20px}.entity-card,.metric{padding:18px;border:1px solid #dce7df;border-radius:14px;background:#fff;display:flex;flex-direction:column;gap:5px}.entity-card span,.metric span,.entity-card small{color:#6f8077}.entity-card b{font-size:20px}.metric b{font-size:28px;color:#1d3928}.metric.verified b{color:#238450}.metric.warning b{color:#ad711d}.metric.danger b{color:#c44545}.fact-workspace{display:grid;grid-template-columns:260px minmax(0,1fr);gap:18px}.panel{background:#fff;border:1px solid #dce7df;border-radius:16px;padding:20px}.panel-title{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;border-bottom:1px solid #edf1ee;padding-bottom:14px;margin-bottom:8px}.panel-title h3{margin:0}.panel-title small,.fact-main small{display:block;color:#738279;margin-top:5px}.store-choice{width:100%;border:0;background:transparent;text-align:left;padding:12px 10px;margin:3px 0;border-radius:10px;color:#2a4134;display:flex;flex-direction:column;gap:3px;cursor:pointer}.store-choice:hover,.store-choice.active{background:#edf7f0;color:#126638}.store-choice small{color:#718076}.boundary{margin-top:22px;padding:13px;background:#fff7e8;border-radius:10px;color:#755729;font-size:13px;line-height:1.7}.boundary p{margin:5px 0 0}.fact-row{display:flex;justify-content:space-between;gap:16px;padding:17px 4px;border-bottom:1px solid #edf1ee}.fact-row:last-child{border:0}.fact-main{min-width:0}.fact-title{display:flex;align-items:center;gap:7px;margin-bottom:8px}.fact-main>b{display:block;font-size:16px;word-break:break-word}.scope{font-size:12px;color:#738279}.fact-actions{display:flex;align-items:flex-start;gap:6px;white-space:nowrap}.empty{padding:42px 20px;color:#748178;text-align:center}.date-range{display:flex;gap:8px;width:100%}.date-range>*{width:50%}.history-item{padding:13px 0;border-bottom:1px solid #edf1ee}.history-item>div:first-child{display:flex;gap:9px;align-items:center}.history-item small{color:#748178}.history-item pre{margin:9px 0;padding:9px;background:#f6f8f6;border-radius:7px;white-space:pre-wrap;word-break:break-word}.history-item p{margin:4px 0}.history-links{margin-top:10px;display:flex;gap:7px;flex-wrap:wrap}.history-links span{margin-left:7px;color:#b33;cursor:pointer}@media(max-width:900px){.fact-stats{grid-template-columns:repeat(2,1fr)}.entity-card{grid-column:span 2}.fact-workspace{grid-template-columns:1fr}.fact-sidebar{display:flex;gap:7px;flex-wrap:wrap}.store-choice{width:auto}.fact-row{flex-direction:column}.fact-actions{flex-wrap:wrap}}
</style>
