create table tenants (id uuid primary key, name varchar(120) not null, created_at timestamp with time zone not null, updated_at timestamp with time zone not null, version bigint not null);
create table users (id uuid primary key, tenant_id uuid not null references tenants(id), email varchar(180) not null, display_name varchar(120) not null, password_hash varchar(255) not null, role varchar(32) not null, created_at timestamp with time zone not null, updated_at timestamp with time zone not null, version bigint not null, unique(tenant_id,email));
create table merchants (id uuid primary key, tenant_id uuid not null references tenants(id), name varchar(160) not null, industry varchar(100) not null, city varchar(80) not null, district varchar(80), status varchar(30) not null, deleted boolean not null default false, created_at timestamp with time zone not null, updated_at timestamp with time zone not null, created_by uuid, updated_by uuid, version bigint not null);
create table brands (id uuid primary key, tenant_id uuid not null references tenants(id), merchant_id uuid not null references merchants(id), name varchar(160) not null, website varchar(500), aliases text not null, services text not null, claims text not null, deleted boolean not null default false, created_at timestamp with time zone not null, updated_at timestamp with time zone not null, created_by uuid, updated_by uuid, version bigint not null);
create table prompt_cases (id uuid primary key, tenant_id uuid not null references tenants(id), merchant_id uuid not null references merchants(id), question text not null, intent varchar(60) not null, locale varchar(40) not null, enabled boolean not null default true, deleted boolean not null default false, created_at timestamp with time zone not null, updated_at timestamp with time zone not null, created_by uuid, updated_by uuid, version bigint not null);
create table competitors (id uuid primary key, tenant_id uuid not null references tenants(id), merchant_id uuid not null references merchants(id), name varchar(160) not null, aliases text not null, deleted boolean not null default false, created_at timestamp with time zone not null, updated_at timestamp with time zone not null, created_by uuid, updated_by uuid, version bigint not null);
create table diagnostic_runs (id uuid primary key, tenant_id uuid not null references tenants(id), merchant_id uuid not null references merchants(id), status varchar(30) not null, provider varchar(40) not null, sample_note varchar(500), created_at timestamp with time zone not null, updated_at timestamp with time zone not null, created_by uuid, updated_by uuid, version bigint not null);
create table answer_snapshots (id uuid primary key, tenant_id uuid not null references tenants(id), diagnostic_run_id uuid not null references diagnostic_runs(id), prompt_case_id uuid not null references prompt_cases(id), model_name varchar(100) not null, response_text text not null, simulated boolean not null, duration_ms bigint not null, created_at timestamp with time zone not null);
create table diagnostic_reports (id uuid primary key, tenant_id uuid not null references tenants(id), diagnostic_run_id uuid not null unique references diagnostic_runs(id), score numeric(5,1) not null, report_markdown text not null, score_snapshot text not null, created_at timestamp with time zone not null, updated_at timestamp with time zone not null, created_by uuid, updated_by uuid, version bigint not null);
create table audit_logs (id uuid primary key, tenant_id uuid not null references tenants(id), actor_id uuid, action varchar(80) not null, entity_type varchar(80) not null, entity_id uuid, summary varchar(500) not null, created_at timestamp with time zone not null);

