<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {api} from '../../api'
import {useMerchantContext} from '../../stores/merchantContext'
const c=useMerchantContext(), dashboard=ref<any>(null), config=ref<any>(null), snapshots=ref<any[]>([]), active=ref<any>(null), loading=ref(false)
async function load(){if(!c.merchant.value)return;const id=c.merchant.value.id;[dashboard.value,config.value,snapshots.value]=await Promise.all([api(`/merchants/${id}/geo-strategy-dashboard`),api(`/merchants/${id}/geo-strategy-config`),api(`/merchants/${id}/geo-diagnoses`)]);active.value=snapshots.value[0]||null}
watch(()=>c.merchant.value?.id,load);onMounted(load)
function merchantId(){const merchant=c.merchant.value;if(!merchant)throw new Error('当前未选择商家');return merchant.id}
function csv(values:any){return Array.isArray(values)?values.join(', '):''}
function splitCsv(value:string){return value.split(/[，,]/).map(item=>item.trim()).filter(Boolean)}
const brandTermsText=computed({get:()=>csv(config.value?.brandTerms),set:(value:string)=>{if(config.value)config.value.brandTerms=splitCsv(value)}})
const ownedDomainsText=computed({get:()=>csv(config.value?.ownedDomains),set:(value:string)=>{if(config.value)config.value.ownedDomains=splitCsv(value)}})
async function run(){loading.value=true;try{active.value=await api(`/merchants/${merchantId()}/geo-diagnoses`,{method:'POST',body:JSON.stringify({})});await load()}finally{loading.value=false}}
async function save(){await api(`/merchants/${merchantId()}/geo-strategy-config`,{method:'PUT',body:JSON.stringify(config.value)});await load()}
async function tasks(){if(!active.value)return;await api(`/merchants/${merchantId()}/geo-diagnoses/${active.value.id}/optimization-tasks`,{method:'POST',body:'{}'});await c.refresh()}
function pct(x:any){return typeof x==='number'?(x*100).toFixed(1)+'%':'—'}
</script>
<template><section class="module-page"><div class="module-heading"><div><span class="eyebrow">BRAND DIAGNOSIS & SOURCE STRATEGY</span><h2>诊断与策略</h2><p>只使用已核验、非演示 AI 观察生成不可变诊断快照；不展示模型内部思维链，也不主张确定因果。</p></div><el-button type="primary" :loading="loading" @click="run">生成 M5 诊断快照</el-button></div>
<div v-if="dashboard" class="metric-grid"><div class="metric-card" v-for="x in [['有效观察',dashboard.metrics.totalObservations],['提及率',pct(dashboard.metrics.mentionRate)],['推荐率',pct(dashboard.metrics.recommendationRate)],['TOP3率',pct(dashboard.metrics.top3Rate)],['事实准确率',pct(dashboard.metrics.factAccuracyRate)]]" :key="x[0]"><small>{{x[0]}}</small><b>{{x[1]}}</b></div></div>
<div class="module-columns"><div class="panel"><h3>监测配置</h3><p class="muted-copy">品牌识别词、目标问题、目标平台及自有来源决定正式诊断口径。</p><el-input v-if="config" v-model="brandTermsText" placeholder="品牌识别词，逗号分隔"/><el-select v-if="config" v-model="config.targetPlatforms" multiple><el-option v-for="p in ['XHS_DIANDIAN','MEITUAN_WENXIAOTUAN','DOUBAO','DEEPSEEK']" :key="p" :value="p"/></el-select><el-input v-if="config" v-model="ownedDomainsText" placeholder="自有域名，逗号分隔"/><el-button :disabled="!config" @click="save">保存监测配置</el-button></div><div class="panel"><h3>平台与问题表现</h3><el-table :data="dashboard?.platformBreakdown||[]"><el-table-column prop="platform" label="平台"/><el-table-column prop="totalObservations" label="样本"/><el-table-column label="提及率"><template #default="s">{{pct(s.row.mentionRate)}}</template></el-table-column><el-table-column label="推荐率"><template #default="s">{{pct(s.row.recommendationRate)}}</template></el-table-column></el-table><h4>问题表现</h4><div v-for="x in dashboard?.questionPerformance||[]" :key="x.questionId" class="data-row"><b>{{x.questionText}}</b><small>样本 {{x.totalObservations}} · 提及 {{pct(x.mentionRate)}} · 推荐 {{pct(x.recommendationRate)}}</small></div></div></div>
<div class="module-columns"><div class="panel"><h3>竞品与信源</h3><div v-for="x in dashboard?.competitors||[]" :key="x.name" class="data-row"><b>{{x.name}}</b><small>竞品出现 {{x.mentionedCount}} 次</small></div><el-divider/><div v-for="x in dashboard?.sources||[]" :key="x.category" class="data-row"><b>{{x.category}}</b><small>引用 {{x.count}} 次</small></div></div><div class="panel"><h3>聚合 Gap 与策略</h3><div v-for="x in dashboard?.strategies||[]" :key="x.code" class="data-row"><el-tag :type="x.priority==='HIGH'?'danger':'warning'">{{x.priority}}</el-tag><b>{{x.title}}</b><small>{{x.reason}}</small></div><el-button type="primary" :disabled="!active" @click="tasks">从当前快照创建整改任务</el-button></div></div>
<div class="panel"><h3>历史诊断快照</h3><div v-for="x in snapshots" :key="x.id" class="data-row"><b>{{x.rule_version||x.ruleVersion}}</b><small>{{x.created_at||x.createdAt}} · 样本 {{x.observation_count||x.observationCount}}</small></div><p class="muted-copy">{{dashboard?.causalityNotice}}</p></div>
</section></template>
