package com.mengwei.localgrowth.observation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mengwei.localgrowth.audit.AuditService;
import com.mengwei.localgrowth.identity.AuthService.Identity;
import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AiObservationService {
  private static final Set<String> PLATFORMS=Set.of("XHS_DIANDIAN","MEITUAN_WENXIAOTUAN","DOUBAO","DEEPSEEK");
  private static final Set<String> STAGES=Set.of("AWARENESS","CONSIDERATION","COMPARISON","DECISION","AFTER_SALE");
  private static final Set<String> MODES=Set.of("MANUAL_APP","MANUAL_WEB"),CHECKS=Set.of("NOT_CHECKED","CORRECT","ERROR"),VERIFICATIONS=Set.of("DRAFT","VERIFIED"),ISSUES=Set.of("WRONG_VALUE","WRONG_ADDRESS","WRONG_PHONE","WRONG_BUSINESS_HOURS","MISSING_KEY_SERVICE","NON_EXISTENT_SERVICE","WRONG_STOREFRONT","UNVERIFIED_CLAIM"),SEVERITIES=Set.of("LOW","MEDIUM","HIGH"),REASONS=Set.of("NOT_MENTIONED","NOT_RECOMMENDED","FACT_ERROR","COMPETITOR_DOMINANCE","MISSING_SERVICE_KNOWLEDGE");
  private final JdbcTemplate jdbc; private final NamedParameterJdbcTemplate named; private final ObjectMapper json; private final AuditService audit;
  public AiObservationService(JdbcTemplate jdbc,NamedParameterJdbcTemplate named,ObjectMapper json,AuditService audit){this.jdbc=jdbc;this.named=named;this.json=json;this.audit=audit;}

  public List<Map<String,Object>> questions(Identity i,UUID merchant,Map<String,String> f){
    merchant(i,merchant); String sql="select q.*,count(o.id) as observation_count from consumer_questions q left join ai_observations o on o.question_id=q.id and o.tenant_id=q.tenant_id and not o.deleted where q.tenant_id=:tenantId and q.merchant_id=:merchantId and not q.deleted"; MapSqlParameterSource p=base(i,merchant);
    if(has(f,"storefrontId")){sql+=" and q.storefront_id=:storefrontId";p.addValue("storefrontId",uuid(f.get("storefrontId")));} if(has(f,"enabled")){sql+=" and q.enabled=:enabled";p.addValue("enabled",Boolean.parseBoolean(f.get("enabled")));} if(has(f,"decisionStage")){sql+=" and q.decision_stage=:decisionStage";p.addValue("decisionStage",f.get("decisionStage"));} if(has(f,"commercialValue")){sql+=" and q.commercial_value=:commercialValue";p.addValue("commercialValue",Integer.valueOf(f.get("commercialValue")));} if(has(f,"keyword")){sql+=" and q.question_text ilike :keyword";p.addValue("keyword","%"+f.get("keyword")+"%");} if(has(f,"platform")){sql+=" and q.target_platforms @> cast(:platform as jsonb)";p.addValue("platform",json(List.of(f.get("platform"))));}
    sql+=" group by q.id order by q.commercial_value desc,q.created_at desc";return named.queryForList(sql,p);
  }
  @Transactional public Map<String,Object> createQuestion(Identity i,UUID merchant,AiObservationController.QuestionInput in){validateQuestion(in);merchant(i,merchant);store(i,merchant,in.storefrontId());UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();MapSqlParameterSource p=base(i,merchant).addValue("id",id).addValue("storefrontId",in.storefrontId()).addValue("questionText",in.questionText()).addValue("city",in.city()).addValue("district",in.district()).addValue("industry",in.industry()).addValue("scenario",in.consumerScenario()).addValue("audience",in.targetAudience()).addValue("budget",in.budgetText()).addValue("stage",in.decisionStage()).addValue("value",in.commercialValue()).addValue("platforms",json(orEmpty(in.targetPlatforms()))).addValue("enabled",in.enabled()==null||in.enabled()).addValue("demo",Boolean.TRUE.equals(in.demo())).addValue("notes",in.notes()).addValue("now",now).addValue("userId",i.userId());named.update("insert into consumer_questions(id,tenant_id,merchant_id,storefront_id,question_text,city,district,industry,consumer_scenario,target_audience,budget_text,decision_stage,commercial_value,target_platforms,enabled,demo,notes,deleted,created_at,updated_at,created_by,updated_by,version) values(:id,:tenantId,:merchantId,:storefrontId,:questionText,:city,:district,:industry,:scenario,:audience,:budget,:stage,:value,cast(:platforms as jsonb),:enabled,:demo,:notes,false,:now,:now,:userId,:userId,0)",p);audit.log(i.tenantId(),i.userId(),"CONSUMER_QUESTION_CREATED","ConsumerQuestion",id,"新建消费者问题");return question(i,merchant,id);}
  public Map<String,Object> question(Identity i,UUID merchant,UUID id){merchant(i,merchant);return one("select q.*,count(o.id) as observation_count from consumer_questions q left join ai_observations o on o.question_id=q.id and o.tenant_id=q.tenant_id and not o.deleted where q.id=:id and q.tenant_id=:tenantId and q.merchant_id=:merchantId and not q.deleted group by q.id",base(i,merchant).addValue("id",id));}
  @Transactional public Map<String,Object> updateQuestion(Identity i,UUID merchant,UUID id,AiObservationController.QuestionInput in){validateQuestion(in);question(i,merchant,id);store(i,merchant,in.storefrontId());OffsetDateTime now=OffsetDateTime.now();MapSqlParameterSource p=base(i,merchant).addValue("id",id).addValue("storefrontId",in.storefrontId()).addValue("questionText",in.questionText()).addValue("city",in.city()).addValue("district",in.district()).addValue("industry",in.industry()).addValue("scenario",in.consumerScenario()).addValue("audience",in.targetAudience()).addValue("budget",in.budgetText()).addValue("stage",in.decisionStage()).addValue("value",in.commercialValue()).addValue("platforms",json(orEmpty(in.targetPlatforms()))).addValue("enabled",in.enabled()==null||in.enabled()).addValue("demo",Boolean.TRUE.equals(in.demo())).addValue("notes",in.notes()).addValue("now",now).addValue("userId",i.userId());named.update("update consumer_questions set storefront_id=:storefrontId,question_text=:questionText,city=:city,district=:district,industry=:industry,consumer_scenario=:scenario,target_audience=:audience,budget_text=:budget,decision_stage=:stage,commercial_value=:value,target_platforms=cast(:platforms as jsonb),enabled=:enabled,demo=:demo,notes=:notes,updated_at=:now,updated_by=:userId,version=version+1 where id=:id and tenant_id=:tenantId and merchant_id=:merchantId and not deleted",p);return question(i,merchant,id);}
  @Transactional public void deleteQuestion(Identity i,UUID merchant,UUID id){question(i,merchant,id);named.update("update consumer_questions set deleted=true,enabled=false,updated_at=:now,updated_by=:userId,version=version+1 where id=:id and tenant_id=:tenantId and merchant_id=:merchantId",base(i,merchant).addValue("id",id).addValue("now",OffsetDateTime.now()).addValue("userId",i.userId()));audit.log(i.tenantId(),i.userId(),"CONSUMER_QUESTION_DISABLED","ConsumerQuestion",id,"停用消费者问题");}

  public List<Map<String,Object>> observations(Identity i,UUID merchant,Map<String,String> f){merchant(i,merchant);String sql="select o.*,q.question_text from ai_observations o join consumer_questions q on q.id=o.question_id and q.tenant_id=o.tenant_id where o.tenant_id=:tenantId and o.merchant_id=:merchantId and not o.deleted";MapSqlParameterSource p=base(i,merchant);for(String key:List.of("questionId","storefrontId"))if(has(f,key)){sql+=" and o."+(key.equals("questionId")?"question_id":"storefront_id")+"=:"+key;p.addValue(key,uuid(f.get(key)));}for(String key:List.of("aiPlatform","factCheckStatus","verificationStatus"))if(has(f,key)){String col=switch(key){case "aiPlatform"->"ai_platform";case "factCheckStatus"->"fact_check_status";default->"verification_status";};sql+=" and o."+col+"=:"+key;p.addValue(key,f.get(key));}for(String key:List.of("merchantMentioned","merchantRecommended"))if(has(f,key)){String col=key.equals("merchantMentioned")?"merchant_mentioned":"merchant_recommended";sql+=" and o."+col+"=:"+key;p.addValue(key,Boolean.parseBoolean(f.get(key)));}if(has(f,"dateFrom")){sql+=" and o.observed_at>=:dateFrom";p.addValue("dateFrom",OffsetDateTime.parse(f.get("dateFrom")));}if(has(f,"dateTo")){sql+=" and o.observed_at<=:dateTo";p.addValue("dateTo",OffsetDateTime.parse(f.get("dateTo")));}return named.queryForList(sql+" order by o.observed_at desc",p);}
  @Transactional public Map<String,Object> createObservation(Identity i,UUID merchant,AiObservationController.ObservationInput in){validateObservation(in);merchant(i,merchant);question(i,merchant,in.questionId());store(i,merchant,in.storefrontId());asset(i,in.screenshotAssetId());UUID id=UUID.randomUUID();writeObservation(i,merchant,id,in,false);audit.log(i.tenantId(),i.userId(),"AI_OBSERVATION_CREATED","AiObservation",id,"人工录入AI观察");return observation(i,merchant,id);}
  @Transactional public Map<String,Object> updateObservation(Identity i,UUID merchant,UUID id,AiObservationController.ObservationInput in){validateObservation(in);observation(i,merchant,id);question(i,merchant,in.questionId());store(i,merchant,in.storefrontId());asset(i,in.screenshotAssetId());writeObservation(i,merchant,id,in,true);return observation(i,merchant,id);}
  private void writeObservation(Identity i,UUID m,UUID id,AiObservationController.ObservationInput in,boolean update){OffsetDateTime now=OffsetDateTime.now();MapSqlParameterSource p=base(i,m).addValue("id",id).addValue("storefrontId",in.storefrontId()).addValue("questionId",in.questionId()).addValue("platform",in.aiPlatform()).addValue("mode",in.observationMode()).addValue("observedAt",in.observedAt()).addValue("location",in.locationText()).addValue("answer",in.rawAnswer()).addValue("screenshot",in.screenshotAssetId()).addValue("mentioned",Boolean.TRUE.equals(in.merchantMentioned())).addValue("recommended",Boolean.TRUE.equals(in.merchantRecommended())).addValue("rank",in.recommendationRank()).addValue("check",in.factCheckStatus()).addValue("sources",json(orEmpty(in.citedSources()))).addValue("competitors",json(orEmpty(in.mentionedCompetitors()))).addValue("verification",in.verificationStatus()).addValue("demo",Boolean.TRUE.equals(in.demo())).addValue("notes",in.notes()).addValue("now",now).addValue("userId",i.userId());if(update)named.update("update ai_observations set storefront_id=:storefrontId,question_id=:questionId,ai_platform=:platform,observation_mode=:mode,observed_at=:observedAt,location_text=:location,raw_answer=:answer,screenshot_asset_id=:screenshot,merchant_mentioned=:mentioned,merchant_recommended=:recommended,recommendation_rank=:rank,fact_check_status=:check,cited_sources=cast(:sources as jsonb),mentioned_competitors=cast(:competitors as jsonb),verification_status=:verification,demo=:demo,notes=:notes,updated_at=:now,updated_by=:userId,version=version+1 where id=:id and tenant_id=:tenantId and merchant_id=:merchantId and not deleted",p);else named.update("insert into ai_observations(id,tenant_id,merchant_id,storefront_id,question_id,ai_platform,observation_mode,observed_at,location_text,raw_answer,screenshot_asset_id,merchant_mentioned,merchant_recommended,recommendation_rank,fact_check_status,cited_sources,mentioned_competitors,verification_status,demo,notes,deleted,created_at,updated_at,created_by,updated_by,version) values(:id,:tenantId,:merchantId,:storefrontId,:questionId,:platform,:mode,:observedAt,:location,:answer,:screenshot,:mentioned,:recommended,:rank,:check,cast(:sources as jsonb),cast(:competitors as jsonb),:verification,:demo,:notes,false,:now,:now,:userId,:userId,0)",p);}
  public Map<String,Object> observation(Identity i,UUID merchant,UUID id){merchant(i,merchant);Map<String,Object> o=one("select o.*,q.question_text from ai_observations o join consumer_questions q on q.id=o.question_id and q.tenant_id=o.tenant_id where o.id=:id and o.tenant_id=:tenantId and o.merchant_id=:merchantId and not o.deleted",base(i,merchant).addValue("id",id));o.put("factIssues",issues(i,merchant,id));return o;}
  @Transactional public void deleteObservation(Identity i,UUID merchant,UUID id){observation(i,merchant,id);named.update("update ai_observations set deleted=true,updated_at=:now,updated_by=:userId,version=version+1 where id=:id and tenant_id=:tenantId and merchant_id=:merchantId",base(i,merchant).addValue("id",id).addValue("now",OffsetDateTime.now()).addValue("userId",i.userId()));}

  public List<Map<String,Object>> issues(Identity i,UUID merchant,UUID observation){observationExists(i,merchant,observation);return named.queryForList("select * from ai_observation_fact_issues where tenant_id=:tenantId and merchant_id=:merchantId and observation_id=:observationId order by created_at desc",base(i,merchant).addValue("observationId",observation));}
  @Transactional public Map<String,Object> createIssue(Identity i,UUID merchant,UUID observation,AiObservationController.FactIssueInput in){validateIssue(in);observationExists(i,merchant,observation);Map<String,Object> fact=in.factId()==null?null:one("select f.id,f.current_version_id,v.value_json::text from merchant_facts f join merchant_fact_versions v on v.id=f.current_version_id and v.tenant_id=f.tenant_id where f.id=:factId and f.tenant_id=:tenantId and f.merchant_id=:merchantId and not f.deleted",base(i,merchant).addValue("factId",in.factId()));UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();MapSqlParameterSource p=base(i,merchant).addValue("id",id).addValue("observationId",observation).addValue("factId",fact==null?null:fact.get("id")).addValue("factVersionId",fact==null?null:fact.get("current_version_id")).addValue("issueType",in.issueType()).addValue("observedValue",in.observedValue()).addValue("expected",fact==null?null:fact.get("value_json")).addValue("severity",in.severity()).addValue("resolved",Boolean.TRUE.equals(in.resolved())).addValue("notes",in.resolutionNotes()).addValue("now",now).addValue("userId",i.userId());named.update("insert into ai_observation_fact_issues(id,tenant_id,merchant_id,observation_id,fact_id,fact_version_id,issue_type,observed_value,expected_value_snapshot,severity,resolved,resolution_notes,created_at,updated_at,created_by,updated_by) values(:id,:tenantId,:merchantId,:observationId,:factId,:factVersionId,:issueType,:observedValue,cast(:expected as jsonb),:severity,:resolved,:notes,:now,:now,:userId,:userId)",p);audit.log(i.tenantId(),i.userId(),"AI_OBSERVATION_FACT_ISSUE_CREATED","AiObservationFactIssue",id,"AI回答事实错误");return one("select * from ai_observation_fact_issues where id=:id and tenant_id=:tenantId",base(i,merchant).addValue("id",id));}
  @Transactional public Map<String,Object> updateIssue(Identity i,UUID merchant,UUID observation,UUID id,AiObservationController.FactIssueUpdate in){observationExists(i,merchant,observation);int n=named.update("update ai_observation_fact_issues set resolved=:resolved,resolution_notes=:notes,updated_at=:now,updated_by=:userId where id=:id and tenant_id=:tenantId and merchant_id=:merchantId and observation_id=:observationId",base(i,merchant).addValue("id",id).addValue("observationId",observation).addValue("resolved",in.resolved()).addValue("notes",in.resolutionNotes()).addValue("now",OffsetDateTime.now()).addValue("userId",i.userId()));if(n!=1)throw notFound();return one("select * from ai_observation_fact_issues where id=:id and tenant_id=:tenantId",base(i,merchant).addValue("id",id));}
  @Transactional public void deleteIssue(Identity i,UUID merchant,UUID observation,UUID id){observationExists(i,merchant,observation);int n=named.update("delete from ai_observation_fact_issues where id=:id and tenant_id=:tenantId and merchant_id=:merchantId and observation_id=:observationId",base(i,merchant).addValue("id",id).addValue("observationId",observation));if(n!=1)throw notFound();}

  public Map<String,Object> dashboard(Identity i,UUID merchant,Map<String,String> f){List<Map<String,Object>> all=observations(i,merchant,f);long total=all.size(),mentioned=all.stream().filter(x->Boolean.TRUE.equals(x.get("merchant_mentioned"))).count(),recommended=all.stream().filter(x->Boolean.TRUE.equals(x.get("merchant_recommended"))).count(),top3=all.stream().filter(x->x.get("recommendation_rank") instanceof Number n&&n.intValue()>=1&&n.intValue()<=3).count(),correct=all.stream().filter(x->"CORRECT".equals(x.get("fact_check_status"))).count(),errors=all.stream().filter(x->"ERROR".equals(x.get("fact_check_status"))).count();Map<String,Object> out=new LinkedHashMap<>();out.put("totalObservations",total);out.put("mentionedCount",mentioned);out.put("recommendedCount",recommended);out.put("top3Count",top3);out.put("factCheckedCount",correct+errors);out.put("factErrorCount",errors);out.put("mentionRate",rate(mentioned,total));out.put("recommendationRate",rate(recommended,total));out.put("top3Rate",rate(top3,total));out.put("factAccuracyRate",rate(correct,correct+errors));out.put("observedPlatformCount",all.stream().map(x->String.valueOf(x.get("ai_platform"))).distinct().count());out.put("platformBreakdown",breakdown(all));out.put("topCompetitors",competitors(all));out.put("recentFactIssues",named.queryForList("select fi.*,o.ai_platform,o.observed_at from ai_observation_fact_issues fi join ai_observations o on o.id=fi.observation_id and o.tenant_id=fi.tenant_id where fi.tenant_id=:tenantId and fi.merchant_id=:merchantId order by fi.created_at desc limit 10",base(i,merchant)));out.put("causalityNotice","指标只反映人工观察到的时间关联，不证明整改动作与AI回答变化存在因果关系。");return out;}
  @Transactional public Map<String,Object> createTask(Identity i,UUID merchant,UUID observationId,String reason){if(!REASONS.contains(reason))throw bad("INVALID_REASON_CODE","不支持的整改原因");Map<String,Object> o=observation(i,merchant,observationId);String marker="AI_OBSERVATION|"+observationId+"|"+reason;var exists=named.queryForList("select * from optimization_tasks where tenant_id=:tenantId and merchant_id=:merchantId and description like :marker and status not in ('DONE','CANCELLED')",base(i,merchant).addValue("marker","%"+marker+"%"));if(!exists.isEmpty())return exists.getFirst();var runs=named.queryForList("select id from diagnostic_runs where tenant_id=:tenantId and merchant_id=:merchantId order by created_at desc limit 1",base(i,merchant));if(runs.isEmpty())throw bad("DIAGNOSTIC_RUN_REQUIRED","请先生成正式诊断后再创建整改任务");String type=reason.equals("FACT_ERROR")?"AI_FACT_CORRECTION":"AI_VISIBILITY";UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();String description="原消费者问题："+o.get("question_text")+"；AI平台："+o.get("ai_platform")+"；是否提及："+o.get("merchant_mentioned")+"；是否推荐："+o.get("merchant_recommended")+"；排名："+o.get("recommendation_rank")+"；回答摘要："+shortText(String.valueOf(o.get("raw_answer")))+"；建议整改方向："+reason+"；source metadata="+marker;MapSqlParameterSource p=base(i,merchant).addValue("id",id).addValue("diagnosticRunId",runs.getFirst().get("id")).addValue("type",type).addValue("title",reason.equals("FACT_ERROR")?"纠正AI回答中的商家事实":"提升AI平台商家可见度").addValue("description",description).addValue("questions",json(List.of(String.valueOf(o.get("question_id"))))).addValue("channels",json(List.of(String.valueOf(o.get("ai_platform"))))).addValue("now",now).addValue("userId",i.userId());named.update("insert into optimization_tasks(id,tenant_id,merchant_id,diagnostic_run_id,task_type,title,description,priority,target_question_ids,recommended_channels,status,created_at,updated_at,created_by,updated_by,version) values(:id,:tenantId,:merchantId,:diagnosticRunId,:type,:title,:description,'HIGH',cast(:questions as jsonb),cast(:channels as jsonb),'TODO',:now,:now,:userId,:userId,0)",p);return named.queryForMap("select * from optimization_tasks where id=:id",new MapSqlParameterSource("id",id));}

  private List<Map<String,Object>> breakdown(List<Map<String,Object>> rows){Map<String,List<Map<String,Object>>> g=new TreeMap<>();for(var x:rows)g.computeIfAbsent(String.valueOf(x.get("ai_platform")),k->new ArrayList<>()).add(x);List<Map<String,Object>> out=new ArrayList<>();for(var e:g.entrySet()){var r=e.getValue();Map<String,Object> x=new LinkedHashMap<>();x.put("platform",e.getKey());x.put("observations",r.size());x.put("mentioned",r.stream().filter(a->Boolean.TRUE.equals(a.get("merchant_mentioned"))).count());x.put("recommended",r.stream().filter(a->Boolean.TRUE.equals(a.get("merchant_recommended"))).count());x.put("top3",r.stream().filter(a->a.get("recommendation_rank") instanceof Number n&&n.intValue()<=3&&n.intValue()>0).count());x.put("factErrors",r.stream().filter(a->"ERROR".equals(a.get("fact_check_status"))).count());out.add(x);}return out;}
  private List<Map<String,Object>> competitors(List<Map<String,Object>> rows){Map<String,Long> counts=new HashMap<>();for(var r:rows)for(Map<String,Object> c:list(r.get("mentioned_competitors")))counts.merge(String.valueOf(c.get("name")),1L,Long::sum);return counts.entrySet().stream().sorted(Map.Entry.<String,Long>comparingByValue().reversed()).map(e->{Map<String,Object>x=new LinkedHashMap<>();x.put("name",e.getKey());x.put("mentions",e.getValue());return x;}).toList();}
  @SuppressWarnings("unchecked") private List<Map<String,Object>> list(Object raw){try{return raw==null?List.of():json.readValue(String.valueOf(raw),new TypeReference<List<Map<String,Object>>>(){});}catch(Exception e){return List.of();}}
  private void validateQuestion(AiObservationController.QuestionInput x){if(!STAGES.contains(x.decisionStage())||x.commercialValue()<1||x.commercialValue()>5)throw bad("INVALID_QUESTION","消费者问题参数不合法");for(Object p:orEmpty(x.targetPlatforms()))if(!PLATFORMS.contains(String.valueOf(p)))throw bad("INVALID_PLATFORM","不支持的AI平台");}
  private void validateObservation(AiObservationController.ObservationInput x){if(!PLATFORMS.contains(x.aiPlatform())||!MODES.contains(x.observationMode())||!CHECKS.contains(x.factCheckStatus())||!VERIFICATIONS.contains(x.verificationStatus())||(x.recommendationRank()!=null&&x.recommendationRank()<1))throw bad("INVALID_OBSERVATION","观察记录参数不合法");}
  private void validateIssue(AiObservationController.FactIssueInput x){if(!ISSUES.contains(x.issueType())||!SEVERITIES.contains(x.severity()))throw bad("INVALID_FACT_ISSUE","事实错误参数不合法");}
  private void merchant(Identity i,UUID m){if(named.queryForList("select id from merchants where id=:merchantId and tenant_id=:tenantId and not deleted",base(i,m)).isEmpty())throw notFound();} private void store(Identity i,UUID m,UUID s){if(s!=null&&named.queryForList("select id from storefronts where id=:storefrontId and tenant_id=:tenantId and merchant_id=:merchantId and not deleted",base(i,m).addValue("storefrontId",s)).isEmpty())throw notFound();}private void asset(Identity i,UUID a){if(a!=null&&jdbc.queryForList("select id from assets where id=? and tenant_id=?",a,i.tenantId()).isEmpty())throw notFound();}private void observationExists(Identity i,UUID m,UUID o){if(named.queryForList("select id from ai_observations where id=:id and tenant_id=:tenantId and merchant_id=:merchantId and not deleted",base(i,m).addValue("id",o)).isEmpty())throw notFound();}private MapSqlParameterSource base(Identity i,UUID merchant){return new MapSqlParameterSource().addValue("tenantId",i.tenantId()).addValue("merchantId",merchant);}private Map<String,Object> one(String sql,MapSqlParameterSource p){var rows=named.queryForList(sql,p);if(rows.isEmpty())throw notFound();return new LinkedHashMap<>(rows.getFirst());}private ApiException bad(String c,String msg){return new ApiException(HttpStatus.BAD_REQUEST,c,msg);}private ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","数据不存在或无权访问");}private boolean has(Map<String,String>f,String k){return f.get(k)!=null&&!f.get(k).isBlank();}private UUID uuid(String x){try{return UUID.fromString(x);}catch(Exception e){throw bad("INVALID_UUID","ID格式不正确");}}private List<?>orEmpty(List<?>x){return x==null?List.of():x;}private String json(Object x){try{return json.writeValueAsString(x);}catch(Exception e){throw new IllegalStateException(e);}}private Double rate(long n,long d){return d==0?null:(double)n/d;}private String shortText(String x){return x.length()<=300?x:x.substring(0,300)+"…";}
}
