package com.mengwei.localgrowth.asset;
import com.mengwei.localgrowth.identity.AuthService.Identity; import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;
import io.minio.*; import java.io.InputStream; import java.time.OffsetDateTime; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile;
@Service public class AssetService {
  private static final Set<String> TYPES=Set.of("image/png","image/jpeg","image/webp"); private static final long MAX=8*1024*1024;
  private final JdbcTemplate jdbc;private final MinioClient minio;private final String bucket;
  public AssetService(JdbcTemplate jdbc,@Value("${app.storage.endpoint}")String endpoint,@Value("${app.storage.access-key}")String access,@Value("${app.storage.secret-key}")String secret,@Value("${app.storage.bucket}")String bucket){this.jdbc=jdbc;this.minio=MinioClient.builder().endpoint(endpoint).credentials(access,secret).build();this.bucket=bucket;}
  public Map<String,Object> upload(Identity i,MultipartFile file){if(file.isEmpty()||file.getSize()>MAX||!TYPES.contains(file.getContentType()))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_IMAGE","仅允许 PNG、JPG、JPEG、WebP，且不超过8MB");try{if(!minio.bucketExists(BucketExistsArgs.builder().bucket(bucket).build()))minio.makeBucket(MakeBucketArgs.builder().bucket(bucket).build());UUID id=UUID.randomUUID();String key="tenants/"+i.tenantId()+"/evidence/"+id+"/"+safeName(file.getOriginalFilename());try(InputStream stream=file.getInputStream()){minio.putObject(PutObjectArgs.builder().bucket(bucket).object(key).stream(stream,file.getSize(),-1).contentType(file.getContentType()).build());}OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into assets values (?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),key,file.getOriginalFilename(),file.getContentType(),file.getSize(),now,now,i.userId(),i.userId(),0L);return asset(i,id);}catch(ApiException e){throw e;}catch(Exception e){throw new ApiException(HttpStatus.BAD_GATEWAY,"ASSET_UPLOAD_FAILED","截图上传失败，未创建证据附件");}}
  public Map<String,Object> asset(Identity i,UUID id){Map<String,Object> a=metadata(i,id);a.put("previewUrl",null);return a;}
  public Map<String,Object> metadata(Identity i,UUID id){var rows=jdbc.queryForList("select id,object_key as \"objectKey\",original_filename as \"originalFilename\",mime_type as \"mimeType\",size,created_at as \"createdAt\" from assets where id=? and tenant_id=?",id,i.tenantId());if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"ASSET_NOT_FOUND","附件不存在或无权访问");return new LinkedHashMap<>(rows.getFirst());}
  public byte[] bytes(Identity i,UUID id){try{String key=(String)metadata(i,id).get("objectKey");try(var response=minio.getObject(GetObjectArgs.builder().bucket(bucket).object(key).build())){return response.readAllBytes();}}catch(ApiException e){throw e;}catch(Exception e){throw new ApiException(HttpStatus.BAD_GATEWAY,"ASSET_READ_FAILED","附件读取失败");}}
  private String safeName(String name){return (name==null?"screenshot":name).replaceAll("[^a-zA-Z0-9._-]","_");}
}
