<script setup lang="ts">
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../../api'
import { useMerchantContext } from '../../stores/merchantContext'
const c=useMerchantContext();const channel=ref('XIAOHONGSHU');const state=ref('idle');const error=ref('');const draft=ref<any>(null);const review=ref<any>(null);const publishAsset=ref<any>(null);const quality=ref({factualityScore:5,platformFitScore:5,usefulnessScore:5,reviewerNotes:'',editedContent:''});const publication=ref({platform:'XIAOHONGSHU',accountName:'',publishedUrl:'',publishedAt:new Date().toISOString().slice(0,16),publishStatus:'PUBLISHED',indexStatus:'PENDING_CHECK',notes:''})
async function generate(t:any){state.value='calling';error.value='';try{draft.value=await api(`/optimization-tasks/${t.id}/real-content`,{method:'POST',body:JSON.stringify({channel:channel.value})});await c.refresh();if(draft.value.generationBlocked){state.value='failed';error.value=draft.value.reason||'资料不足'}else{state.value='success';ElMessage.success('生成成功')}}catch(e:any){state.value='failed';error.value=e.message}}
async function generateMock(t:any){try{draft.value=await api(`/optimization-tasks/${t.id}/content-assets`,{method:'POST',body:JSON.stringify({channel:channel.value})});await c.refresh();state.value='success';ElMessage.success('模板Mock草稿已生成')}catch(e:any){state.value='failed';error.value=e.message}}
async function submit(status:string){if(!review.value)return;const x=await api(`/content-assets/${review.value.id}/review`,{method:'PATCH',body:JSON.stringify({status,...quality.value})});Object.assign(review.value,x);review.value=null;ElMessage.success('人工验收已保存')}
async function approve(a:any){await api(`/content-assets/${a.id}/review`,{method:'PATCH',body:JSON.stringify({status:'APPROVED'})});await c.refresh();ElMessage.success('内容已通过审核')}
async function publish(){if(!publishAsset.value)return;await api(`/content-assets/${publishAsset.value.id}/publications`,{method:'POST',body:JSON.stringify({...publication.value,publishedAt:new Date(publication.value.publishedAt).toISOString()})});publishAsset.value=null;await c.refresh();ElMessage.success('发布登记已保存')}
</script>
<template>
  <section class="module-page"><div class="module-heading"><div><span class="eyebrow">EXECUTION CENTER</span><h2>执行中心</h2><p>从Gap生成任务，使用Mock或DeepSeek生成内容，再由人工验收、审核和登记发布。</p></div></div>
    <div class="execution-guide"><b>操作引导</b><span>1. 选择平台</span><span>2. 选择优化任务</span><span>3. 点击“用AI生成内容”</span><span>4. 在内容资产中进行人工验收</span></div>
    <div class="toolbar"><el-select v-model="channel"><el-option v-for="x in ['WEBSITE','XIAOHONGSHU','DIANPING','DOUYIN','WECHAT','ZHIHU']" :key="x" :value="x" :label="x"/></el-select><el-tag :type="c.data.provider?.configured?'success':'warning'">DeepSeek {{c.data.provider?.configured?'可用':'未配置'}}</el-tag></div>
    <el-alert v-if="state==='calling'" title="正在调用DeepSeek……" type="info" :closable="false"/><el-alert v-if="state==='success'" title="生成成功" type="success" :closable="false"/><el-alert v-if="state==='failed'" :title="`生成失败：${error}`" type="error" :closable="false"/>
    <div class="module-columns"><div class="panel"><h3>30天优化任务（{{c.data.tasks.length}}）</h3><div v-for="t in c.data.tasks" :key="t.id" class="data-row task-row"><div><b>{{t.title}}</b><small>{{t.task_type}} · {{t.priority}} · {{t.status}}</small></div><div class="asset-actions"><el-button size="small" @click="generateMock(t)">模板 Mock</el-button><el-button type="primary" size="small" :disabled="!c.data.provider?.configured" :loading="state==='calling'" @click="generate(t)">用AI生成内容</el-button></div></div></div>
      <div class="panel"><h3>内容资产（{{c.data.assets.length}}）</h3><div v-for="a in c.data.assets.slice(0,10)" :key="a.id" class="data-row"><div><b>{{a.title}}</b><small>{{a.channel}} · {{a.review_status}} · 发布 {{a.latest_publish_status||'未登记'}} · 收录 {{a.latest_index_status||'未知'}}</small></div><div class="asset-actions"><el-button v-if="a.review_status==='DRAFT'" size="small" @click="review=a;quality.editedContent=a.content||''">人工验收</el-button><el-button v-if="a.review_status==='PENDING_REVIEW'" size="small" type="success" @click="approve(a)">通过审核</el-button><el-button v-if="a.review_status==='APPROVED'" size="small" type="primary" @click="publishAsset=a;publication.platform=a.channel">登记发布</el-button></div></div></div></div>
    <div v-if="draft" class="draft-card"><h3>生成草稿 · {{draft.model}}</h3><p>使用事实：{{(draft.usedFacts||[]).join('、')||'已验证商家资料'}}</p><pre>{{draft.generatedContent}}</pre><p v-if="draft.riskFlags?.length" class="risk-flags">风险：{{draft.riskFlags.join('、')}}</p></div>
    <div v-if="review" class="panel review-panel"><h3>人工内容验收</h3><el-input v-model="quality.editedContent" type="textarea" :rows="7"/><div class="quality-scores"><el-input-number v-model="quality.factualityScore" :min="1" :max="5"/><el-input-number v-model="quality.platformFitScore" :min="1" :max="5"/><el-input-number v-model="quality.usefulnessScore" :min="1" :max="5"/></div><el-input v-model="quality.reviewerNotes" placeholder="验收备注或拒绝原因"/><el-button type="primary" @click="submit('PENDING_REVIEW')">确认并提交审核</el-button><el-button type="danger" @click="submit('REJECTED')">拒绝</el-button></div>
    <div v-if="publishAsset" class="panel review-panel"><h3>登记发布</h3><el-input v-model="publication.accountName" placeholder="发布账号名称"/><el-input v-model="publication.publishedUrl" placeholder="发布链接"/><el-select v-model="publication.publishStatus"><el-option v-for="x in ['PENDING','PUBLISHED','FAILED','REMOVED','LIMITED']" :key="x" :value="x"/></el-select><el-select v-model="publication.indexStatus"><el-option v-for="x in ['UNKNOWN','PENDING_CHECK','INDEXED','NOT_INDEXED']" :key="x" :value="x"/></el-select><el-input v-model="publication.notes" placeholder="备注"/><el-button type="primary" :disabled="!publication.accountName" @click="publish">保存发布登记</el-button></div>
  </section>
</template>
