package com.mengwei.localgrowth.merchant;
import com.mengwei.localgrowth.fact.FactCenterService;
import com.mengwei.localgrowth.audit.AuditService; import com.mengwei.localgrowth.identity.AuthService.Identity; import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;
import java.time.OffsetDateTime; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class MerchantService {
  private final JdbcTemplate jdbc; private final AuditService audit; private final FactCenterService facts; public MerchantService(JdbcTemplate jdbc,AuditService audit,FactCenterService facts){this.jdbc=jdbc;this.audit=audit;this.facts=facts;}
  public List<Map<String,Object>> merchants(Identity i){return jdbc.queryForList("select id,name,industry,city,district,status,version,created_at,updated_at from merchants where tenant_id=? and deleted=false order by updated_at desc",i.tenantId());}
  public Map<String,Object> merchant(Identity i,UUID id){return one("select id,name,industry,city,district,status,version,created_at,updated_at from merchants where id=? and tenant_id=? and deleted=false",id,i.tenantId());}
  @Transactional public Map<String,Object> createMerchant(Identity i,String name,String industry,String city,String district){UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into merchants values (?,?,?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),name,industry,city,district,"DRAFT",false,now,now,i.userId(),i.userId(),0L);audit.log(i.tenantId(),i.userId(),"MERCHANT_CREATED","Merchant",id,"创建商家："+name);facts.initializeMerchant(i,id,name);return merchant(i,id);}
  public Map<String,Object> updateMerchant(Identity i,UUID id,String name,String industry,String city,String district,String status){merchant(i,id); jdbc.update("update merchants set name=?,industry=?,city=?,district=?,status=?,updated_at=?,updated_by=?,version=version+1 where id=? and tenant_id=?",name,industry,city,district,status,OffsetDateTime.now(),i.userId(),id,i.tenantId());audit.log(i.tenantId(),i.userId(),"MERCHANT_UPDATED","Merchant",id,"更新商家资料");return merchant(i,id);}
  public List<Map<String,Object>> brands(Identity i,UUID merchantId){merchant(i,merchantId);return jdbc.queryForList("select id,name,website,aliases,services,claims,version,updated_at from brands where merchant_id=? and tenant_id=? and deleted=false order by updated_at desc",merchantId,i.tenantId());}
  public Map<String,Object> addBrand(Identity i,UUID merchantId,String name,String website,String aliases,String services,String claims){merchant(i,merchantId);UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into brands values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),merchantId,name,website,aliases,services,claims,false,now,now,i.userId(),i.userId(),0L);audit.log(i.tenantId(),i.userId(),"BRAND_CREATED","Brand",id,"创建品牌知识档案："+name);return one("select id,name,website,aliases,services,claims,version,updated_at from brands where id=? and tenant_id=?",id,i.tenantId());}
  public List<Map<String,Object>> prompts(Identity i,UUID merchantId){merchant(i,merchantId);return jdbc.queryForList("select id,question,intent,locale,category,city,district,intent_level,enabled,sort_order,version,updated_at from prompt_cases where merchant_id=? and tenant_id=? and deleted=false order by sort_order, created_at",merchantId,i.tenantId());}
  public Map<String,Object> addPrompt(Identity i,UUID merchantId,String question,String category,String city,String district,String intentLevel,boolean enabled,int sortOrder,String locale){merchant(i,merchantId);UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into prompt_cases (id,tenant_id,merchant_id,question,intent,locale,enabled,deleted,created_at,updated_at,created_by,updated_by,version,category,city,district,intent_level,sort_order) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),merchantId,question,category,locale,enabled,false,now,now,i.userId(),i.userId(),0L,category,city,district,intentLevel,sortOrder);audit.log(i.tenantId(),i.userId(),"PROMPT_CREATED","PromptCase",id,"添加 "+category+" 测试问题");return one("select id,question,intent,locale,category,city,district,intent_level,enabled,sort_order,version,updated_at from prompt_cases where id=? and tenant_id=?",id,i.tenantId());}
  public List<Map<String,Object>> competitors(Identity i,UUID merchantId){merchant(i,merchantId);return jdbc.queryForList("select id,name,aliases,version,updated_at from competitors where merchant_id=? and tenant_id=? and deleted=false order by name",merchantId,i.tenantId());}
  public Map<String,Object> addCompetitor(Identity i,UUID merchantId,String name,String aliases){merchant(i,merchantId);UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into competitors values (?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),merchantId,name,aliases,false,now,now,i.userId(),i.userId(),0L);audit.log(i.tenantId(),i.userId(),"COMPETITOR_CREATED","CompetitorBrand",id,"添加竞争品牌："+name);return one("select id,name,aliases,version,updated_at from competitors where id=? and tenant_id=?",id,i.tenantId());}
  private Map<String,Object> one(String sql,Object... args){var result=jdbc.queryForList(sql,args);if(result.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"NOT_FOUND","数据不存在或无权访问");return result.getFirst();}
}
