package com.mengwei.localgrowth.execution;
import com.mengwei.localgrowth.identity.AuthService.Identity;import com.mengwei.localgrowth.shared.TenantAccess;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import jakarta.validation.constraints.NotNull;import java.time.*;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") public class ExecutionController {private final ExecutionService s;private final TenantAccess a;public ExecutionController(ExecutionService s,TenantAccess a){this.s=s;this.a=a;}private Identity i(String h){return a.identity(h);}
@GetMapping("/merchants/{id}/optimization-tasks")List<Map<String,Object>> tasks(@RequestHeader("Authorization")String h,@PathVariable UUID id){return s.tasks(i(h),id);}
@PostMapping("/diagnostic-reports/{id}/optimization-tasks")List<Map<String,Object>> generate(@RequestHeader("Authorization")String h,@PathVariable UUID id){return s.generateTasks(i(h),id);}
@PatchMapping("/optimization-tasks/{id}")Map<String,Object> update(@RequestHeader("Authorization")String h,@PathVariable UUID id,@Valid @RequestBody TaskUpdate r){return s.updateTask(i(h),id,r.status(),r.assignee(),r.dueDate());}
@GetMapping("/merchants/{id}/content-assets")List<Map<String,Object>> contents(@RequestHeader("Authorization")String h,@PathVariable UUID id){return s.contents(i(h),id);}
@PostMapping("/optimization-tasks/{id}/content-assets")Map<String,Object> content(@RequestHeader("Authorization")String h,@PathVariable UUID id,@Valid @RequestBody ContentRequest r){return s.generateContent(i(h),id,r.channel());}
@PatchMapping("/content-assets/{id}/review")Map<String,Object> review(@RequestHeader("Authorization")String h,@PathVariable UUID id,@Valid @RequestBody ReviewRequest r){return s.reviewContent(i(h),id,r.status(),r.editedContent(),r.factualityScore(),r.platformFitScore(),r.usefulnessScore(),r.reviewerNotes(),r.rejectionReasons());}
@PostMapping("/content-assets/{id}/publications")Map<String,Object> publish(@RequestHeader("Authorization")String h,@PathVariable UUID id,@Valid @RequestBody PublicationRequest r){return s.publish(i(h),id,r.platform(),r.accountName(),r.publishedUrl(),r.publishedAt(),r.screenshotAssetId(),r.publishStatus(),r.indexStatus(),r.notes());}
@GetMapping("/merchants/{id}/retest-plans")List<Map<String,Object>> retests(@RequestHeader("Authorization")String h,@PathVariable UUID id){return s.retests(i(h),id);}
@PostMapping("/diagnostic-runs/{id}/retest-plans")List<Map<String,Object>> createRetests(@RequestHeader("Authorization")String h,@PathVariable UUID id){return s.createRetests(i(h),id);}
public record TaskUpdate(@NotBlank String status,UUID assignee,LocalDate dueDate){}public record ContentRequest(@NotBlank String channel){}public record ReviewRequest(@NotBlank String status,String editedContent,Integer factualityScore,Integer platformFitScore,Integer usefulnessScore,String reviewerNotes,List<String> rejectionReasons){}public record PublicationRequest(@NotBlank String platform,@NotBlank String accountName,String publishedUrl,@NotNull OffsetDateTime publishedAt,UUID screenshotAssetId,@NotBlank String publishStatus,String indexStatus,String notes){}
}
