package com.mengwei.localgrowth.execution;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mengwei.localgrowth.audit.AuditService;
import com.mengwei.localgrowth.identity.AuthService.Identity;
import com.mengwei.localgrowth.model.OpenAiCompatibleProvider;
import com.mengwei.localgrowth.shared.ApiExceptionHandler.ApiException;
import java.time.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service;

@Service public class ExecutionService {
  private final JdbcTemplate jdbc; private final AuditService audit; private final OpenAiCompatibleProvider ai; private final ObjectMapper json = new ObjectMapper();
  private static final Set<String> CHANNELS=Set.of("WEBSITE","XIAOHONGSHU","DIANPING","DOUYIN","WECHAT","ZHIHU","BAIDU_CONTENT","LOCAL_MEDIA");
  private static final Set<String> TASKS=Set.of("ENTITY_PROFILE","LOCAL_LISTING","FAQ_CONTENT","LOCATION_CONTENT","PRICE_CONTENT","CASE_STUDY","COMPARISON_CONTENT","THIRD_PARTY_CITATION","REVIEW_OPERATION");
  public ExecutionService(JdbcTemplate jdbc,AuditService audit,OpenAiCompatibleProvider ai){this.jdbc=jdbc;this.audit=audit;this.ai=ai;}
  public List<Map<String,Object>> tasks(Identity i,UUID merchant){assertMerchant(i,merchant);return jdbc.queryForList("select * from optimization_tasks where tenant_id=? and merchant_id=? order by due_date nulls last, priority desc, created_at",i.tenantId(),merchant);}
  public List<Map<String,Object>> generateTasks(Identity i,UUID reportId){
    var report=one("select r.id,r.diagnostic_run_id,d.merchant_id from diagnostic_reports r join diagnostic_runs d on d.id=r.diagnostic_run_id where r.id=? and r.tenant_id=?",reportId,i.tenantId()); UUID merchant=(UUID)report.get("merchant_id"), run=(UUID)report.get("diagnostic_run_id");
    var brand=one("select name,website,services,claims from brands where merchant_id=? and tenant_id=? and deleted=false order by created_at limit 1",merchant,i.tenantId()); var now=OffsetDateTime.now(); LocalDate start=now.toLocalDate();
    Object[][] defs={{"ENTITY_PROFILE","补齐商家实体资料","补充官网/事实页、地址、服务、营业时间和联系方式，所有字段必须可核验。","HIGH","WEBSITE,BAIDU_CONTENT"},{"LOCAL_LISTING","统一本地门店资料","核对大众点评、美团、地图平台的名称、地址、电话、营业时间和服务范围。","HIGH","DIANPING,LOCAL_MEDIA"},{"FAQ_CONTENT","补齐高频问题 FAQ","围绕问题集中的价格、预约、服务流程问题制作事实型 FAQ。","HIGH","WEBSITE,XIAOHONGSHU"},{"LOCATION_CONTENT","制作本地位置内容","补充九江镇到店路线、停车、营业时间等可验证位置信息。","MEDIUM","XIAOHONGSHU,DIANPING"},{"PRICE_CONTENT","制作价格说明内容","仅使用已确认的价格区间或明确说明以现场/客服确认为准，禁止编造价格。","MEDIUM","WEBSITE,WECHAT"},{"CASE_STUDY","补充真实案例","收集客户授权的真实案例、过程和结果，缺少证据时不得发布。","MEDIUM","WEBSITE,XIAOHONGSHU"},{"COMPARISON_CONTENT","制作客观对比内容","针对竞品高频问题说明选择维度，不贬损、不虚构竞品信息。","MEDIUM","ZHIHU,WEBSITE"},{"THIRD_PARTY_CITATION","补充第三方引用","寻找真实可核验的本地媒体、协会或平台资料作为引用来源。","LOW","LOCAL_MEDIA,BAIDU_CONTENT"}};
    List<Map<String,Object>> out=new ArrayList<>(); for(int n=0;n<defs.length;n++){String type=(String)defs[n][0]; if(!TASKS.contains(type))continue; long exists=jdbc.queryForObject("select count(*) from optimization_tasks where tenant_id=? and diagnostic_run_id=? and task_type=?",Long.class,i.tenantId(),run,type);if(exists>0)continue;UUID id=UUID.randomUUID();String channels=json(defs[n][4].toString().split(","));OffsetDateTime t=now.plusDays(Math.min(30,n*3));jdbc.update("insert into optimization_tasks (id,tenant_id,merchant_id,diagnostic_run_id,task_type,title,description,priority,target_question_ids,recommended_channels,due_date,status,created_at,updated_at,created_by,updated_by,version) values (?,?,?,?,?,?,?,?,?::jsonb,?::jsonb,?,?,?,?,?,?)",id,i.tenantId(),merchant,run,type,defs[n][1],defs[n][2],defs[n][3],"[]",channels,t.toLocalDate(),"TODO",now,now,i.userId(),i.userId(),0L);out.add(task(i,id));}
    audit.log(i.tenantId(),i.userId(),"OPTIMIZATION_PLAN_GENERATED","OptimizationTask",run,"从正式诊断生成 "+out.size()+" 项30天优化任务");return out;
  }
  public Map<String,Object> updateTask(Identity i,UUID id,String status,UUID assignee,LocalDate dueDate){var t=one("select id,merchant_id from optimization_tasks where id=? and tenant_id=?",id,i.tenantId());if(!Set.of("TODO","IN_PROGRESS","PENDING_REVIEW","DONE","CANCELLED").contains(status))throw bad("TASK_STATUS_INVALID","任务状态不合法");jdbc.update("update optimization_tasks set status=?,assignee=?,due_date=?,completed_at=?,updated_at=? where id=? and tenant_id=?",status,assignee,dueDate,"DONE".equals(status)?OffsetDateTime.now():null,OffsetDateTime.now(),id,i.tenantId());return task(i,id);}
  public List<Map<String,Object>> contents(Identity i,UUID merchant){assertMerchant(i,merchant);return jdbc.queryForList("select c.*,t.task_type,t.title as task_title from content_assets c join optimization_tasks t on t.id=c.source_task_id where c.tenant_id=? and c.merchant_id=? order by c.scheduled_at nulls last,c.created_at desc",i.tenantId(),merchant);}
  public Map<String,Object> generateContent(Identity i,UUID taskId,String channel){if(!CHANNELS.contains(channel))throw bad("CHANNEL_INVALID","内容渠道不合法");var task=one("select t.*,m.name merchant_name,m.city,m.district from optimization_tasks t join merchants m on m.id=t.merchant_id where t.id=? and t.tenant_id=?",taskId,i.tenantId());var brand=one("select name,website,services,claims from brands where merchant_id=? and tenant_id=? and deleted=false order by created_at limit 1",task.get("merchant_id"),i.tenantId());String facts="品牌："+brand.get("name")+"；服务："+brand.get("services")+"；已验证主张："+brand.get("claims")+"；官网："+brand.get("website");String title=channelTitle(channel,(String)task.get("title"));String content=buildContent(channel,(String)task.get("title"),facts,(String)task.get("city"),(String)task.get("district"));List<String> risks=new ArrayList<>();if("PRICE_CONTENT".equals(task.get("task_type")))risks.add("PRICE_CONFIRMATION_REQUIRED");if("CASE_STUDY".equals(task.get("task_type")))risks.add("CASE_EVIDENCE_REQUIRED");if(content.matches(".*(第一|最好|百分之百|保证).*"))risks.add("ABSOLUTE_CLAIM");UUID id=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into content_assets (id,tenant_id,merchant_id,source_task_id,channel,title,content,fact_snapshot,prompt_version,generation_version,human_edited_content,risk_flags,review_status,created_at,updated_at,created_by,updated_by,version) values (?,?,?,?,?,?,?,?::jsonb,?,?,?,?::jsonb,?,?,?,?,?,?)",id,i.tenantId(),task.get("merchant_id"),taskId,channel,title,content,json(facts),"execution-v0.3","template-v1",null,json(risks),"DRAFT",now,now,i.userId(),i.userId(),0L);return content(i,id);}
  public Map<String,Object> reviewContent(Identity i,UUID id,String status,String edited,Integer factuality,Integer fit,Integer usefulness,String notes,List<String> reasons){if(!Set.of("DRAFT","PENDING_REVIEW","APPROVED","REJECTED","PUBLISHED").contains(status))throw bad("REVIEW_STATUS_INVALID","审核状态不合法");if(factuality!=null&&!validScore(factuality)||fit!=null&&!validScore(fit)||usefulness!=null&&!validScore(usefulness))throw bad("QUALITY_SCORE_INVALID","质量评分必须为1至5分");one("select id from content_assets where id=? and tenant_id=?",id,i.tenantId());String rejection=json(reasons==null?List.of():reasons);jdbc.update("update content_assets set review_status=?,human_edited_content=?,factuality_score=?,platform_fit_score=?,usefulness_score=?,reviewer_notes=?,rejection_reasons=?::jsonb,reviewed_at=?,reviewed_by=?,updated_at=? where id=? and tenant_id=?",status,edited,factuality,fit,usefulness,notes,rejection,OffsetDateTime.now(),i.userId(),OffsetDateTime.now(),id,i.tenantId());return content(i,id);}
  private boolean validScore(Integer score){return score>=1&&score<=5;}
  public Map<String,Object> publish(Identity i,UUID id,String platform,String account,String url,OffsetDateTime at,UUID screenshot,String publishStatus,String index,String notes){if(!CHANNELS.contains(platform))throw bad("CHANNEL_INVALID","发布平台不合法");if(!Set.of("PENDING","PUBLISHED","FAILED","REMOVED","LIMITED").contains(publishStatus))throw bad("PUBLISH_STATUS_INVALID","发布状态不合法");one("select id from content_assets where id=? and tenant_id=?",id,i.tenantId());UUID pid=UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into content_publications (id,tenant_id,content_asset_id,platform,account_name,published_url,published_at,screenshot_asset_id,index_status,notes,created_at,updated_at,created_by,updated_by,version,publish_status) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",pid,i.tenantId(),id,platform,account,url,at,screenshot,index==null?"UNKNOWN":index,notes,now,now,i.userId(),i.userId(),0L,publishStatus);if("PUBLISHED".equals(publishStatus))jdbc.update("update content_assets set review_status='PUBLISHED',updated_at=? where id=? and tenant_id=?",now,id,i.tenantId());return one("select * from content_publications where id=? and tenant_id=?",pid,i.tenantId());}
  public List<Map<String,Object>> retests(Identity i,UUID merchant){assertMerchant(i,merchant);return jdbc.queryForList("select * from retest_plans where tenant_id=? and merchant_id=? order by planned_at",i.tenantId(),merchant);}
  public List<Map<String,Object>> createRetests(Identity i,UUID runId){var run=one("select merchant_id from diagnostic_runs where id=? and tenant_id=?",runId,i.tenantId());UUID merchant=(UUID)run.get("merchant_id");OffsetDateTime now=OffsetDateTime.now();List<Map<String,Object>> out=new ArrayList<>();for(Object[] x:new Object[][]{{"DAY_14",14},{"DAY_30",30}}){long c=jdbc.queryForObject("select count(*) from retest_plans where diagnostic_run_id=? and label=?",Long.class,runId,x[0]);if(c>0)continue;UUID id=UUID.randomUUID();jdbc.update("insert into retest_plans values (?,?,?,?,?,?,?,?,?,?,?,?)",id,i.tenantId(),merchant,runId,x[0],now.toLocalDate().plusDays((Integer)x[1]),"PLANNED",now,now,i.userId(),i.userId(),0L);out.add(one("select * from retest_plans where id=?",id));}return out;}
  private Map<String,Object> task(Identity i,UUID id){return one("select * from optimization_tasks where id=? and tenant_id=?",id,i.tenantId());}private Map<String,Object> content(Identity i,UUID id){return one("select * from content_assets where id=? and tenant_id=?",id,i.tenantId());}private void assertMerchant(Identity i,UUID id){one("select id from merchants where id=? and tenant_id=? and deleted=false",id,i.tenantId());}private Map<String,Object> one(String sql,Object...a){var r=jdbc.queryForList(sql,a);if(r.isEmpty())throw bad("NOT_FOUND","数据不存在或无权访问");return r.getFirst();}private ApiException bad(String c,String m){return new ApiException(HttpStatus.BAD_REQUEST,c,m);}private String json(Object o){try{return json.writeValueAsString(o instanceof String?List.of(o):o);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}private String channelTitle(String c,String t){return switch(c){case "XIAOHONGSHU"->"本地攻略｜"+t;case "DIANPING"->"门店服务说明｜"+t;case "WEBSITE"->"服务事实页｜"+t;default->t;};}private String buildContent(String c,String t,String facts,String city,String district){String prefix=switch(c){case "XIAOHONGSHU"->"本地消费攻略：";case "DIANPING"->"门店信息：";case "WEBSITE"->"服务说明：";default->"内容草稿：";};return prefix+t+"\n\n适用区域："+city+" "+district+"。\n"+facts+"\n\n以上内容仅整理已录入的商家资料；价格、案例、效果和预约信息请以商家确认及实际服务为准。发布前请人工审核。";}
}
